#!/usr/bin/env bash
# ============================================================
# clean.sh — remove build artifacts, working archives, and
#            stray junk from the repo root.
#
# Safe to re-run. Touches only known-disposable files.
# NEVER touches src/, resources/, setup/01-*, setup/02-*,
# public/, docker/, docs/, tools/.
# ============================================================

set -euo pipefail

if [ ! -f docker-compose.yml ] || [ ! -d src ]; then
    echo "✗ Run this script from the repo root (where docker-compose.yml lives)."
    exit 1
fi

removed=0

remove() {
    if [ -e "$1" ] || [ -L "$1" ]; then
        rm -rf -- "$1"
        echo "  removed: $1"
        removed=$((removed + 1))
    fi
}

echo "── Empty stray files at repo root ──────────────────"
# These are usually from misused shell redirections / PHP error output
# captured as filenames. Only delete if zero-byte.
for f in 0 7 74 Array default develop no; do
    if [ -f "$f" ] && [ ! -s "$f" ]; then
        remove "$f"
    fi
done

echo ""
echo "── Backup / leftover .orig files ───────────────────"
remove src/setup/tables.sql.orig
remove tools/compile.php.orig
# Look for any other .orig backups we missed
find . -maxdepth 3 -name '*.orig' -not -path './.git/*' 2>/dev/null | while read -r f; do
    remove "$f"
done

echo ""
echo "── Old fix bundles ─────────────────────────────────"
# Any fix1XX directory left over at repo root from earlier patch deliveries
for d in fix1[0-9][0-9]; do
    [ -d "$d" ] && remove "$d"
done

echo ""
echo "── Nested junk under setup/ ────────────────────────"
remove setup/fix124
remove setup/setup
# Any other nested fix dir under setup/
for d in setup/fix1[0-9][0-9]; do
    [ -d "$d" ] && remove "$d"
done

echo ""
echo "── Working archives and patches in repo root ───────"
remove astrx_full_repo_compile_links_fixed.zip
remove astrx_full_repo_fixed_compile_api_js_clean.zip
remove astrx_compile_prefix_benchmark.patch
remove astrx_template_cache_index_source.patch
# Any astrx_*.zip or astrx_*.patch that snuck in
for f in astrx_*.zip astrx_*.patch; do
    [ -f "$f" ] && remove "$f"
done

echo ""
echo "── Build outputs (rebuild with: php tools/compile.php) ──"
# build/astrx.compiled.php is generated; safe to delete.
remove build/astrx.compiled.php
# Also delete generated front controllers if they were generated by compile.php
# (NOT the canonical public/index.php, which we never touch).
# public/compiled.php is generated by tools/compile.php. Comment the next
# line if you've hand-edited it.
# remove public/compiled.php

echo ""
echo "── Misc captures ───────────────────────────────────"
remove cachegrind
# Cachegrind output files from Xdebug, if present
find . -maxdepth 2 -name 'cachegrind.out.*' -not -path './.git/*' 2>/dev/null | while read -r f; do
    remove "$f"
done

echo ""
echo "── Parallel working copies ─────────────────────────"
# astrx_clean_fixed/ is a duplicate working copy left over from
# earlier debugging. Uncomment if you no longer need it.
# remove astrx_clean_fixed
if [ -d astrx_clean_fixed ]; then
    echo "  skipped: astrx_clean_fixed/  (uncomment the rm in clean.sh if you want it gone)"
fi

echo ""
echo "────────────────────────────────────────────────────"
echo "Removed $removed item(s)."
echo ""
echo "What remains under the repo root should be:"
echo "  README.md  docker-compose.yml  clean.sh"
echo "  docker/   docs/   public/   resources/   setup/"
echo "  src/   tools/   .gitignore (if any)"
