version: '3'

services:
    nginx:
        tty: true
        restart: always
        container_name: container.nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./public:/app/public
            - ./src:/app/src
            - ./resources:/app/resources
        networks:
            - php-network
        depends_on:
          - phpfpm
    phpfpm:
      user: "1000:100"
      tty: true
      restart: always
      container_name: container.phpfpm
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      volumes:
        - ./public:/app/public
        - ./src:/app/src
        - ./resources:/app/resources
      networks:
        - php-network
    mariadb:
        tty: true
        restart: always
        container_name: container.mariadb
        image: mariadb
        ports:
            - '3306:3306'
        volumes:
            - './docker/mysql/config/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro'
            - './setup:/docker-entrypoint-initdb.d'
            #- './docker/mysql/dbdata:/var/lib/mysql'
        networks:
            - php-network
        environment:
            MARIADB_ROOT_PASSWORD_HASH: "*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19"
            MYSQL_DATABASE: astrx

networks:
  php-network:
    driver: bridge
