//! Cross-check: `websearch::pdftext` reproduces the Python
//! `websearch.pdftext` byte-for-byte on minimal PDF blobs — a
//! FlateDecode-compressed content stream (literal + `TJ` array + hex
//! string), an uncompressed stream, `/Title` (literal, octal-escaped,
//! and unsupported hex forms), literal escapes/octal, `max_chars`
//! truncation, and empty/garbage input.
//!
//! @generated by tests/regen_pdftext_goldens.py — DO NOT EDIT BY HAND.
//! Regenerate:
//!   PYTHONPATH=legacy-python/websearch python3 \
//!     crates/websearch/tests/regen_pdftext_goldens.py \
//!     > crates/websearch/tests/xcheck_pdftext.rs
//!
//! Inputs and the UTF-8 of each expected (latin-1) output are hex so
//! both sides see identical bytes; compressed streams are embedded from
//! `zlib.compress`, so Python and Rust inflate the very same input.

struct Fx {
    name: &'static str,
    max_chars: usize,
    input: &'static str,
    text: &'static str,
    title: &'static str,
}

fn unhex(s: &str) -> Vec<u8> {
    let b = s.as_bytes();
    let mut out = Vec::with_capacity(b.len() / 2);
    let mut i = 0;
    while i + 1 < b.len() {
        let hi = (b[i] as char).to_digit(16).unwrap();
        let lo = (b[i + 1] as char).to_digit(16).unwrap();
        out.push((hi * 16 + lo) as u8);
        i += 2;
    }
    out
}

const FIXTURES: &[Fx] = &[
    Fx {
        name: "flate_literal_tj_hex",
        max_chars: 2000000,
        input: "255044462d312e340a342030206f626a0a3c3c202f466c6174654465636f6465202f4c656e677468203637203e3e0a73747265616d0a789c730a51d0773354303452084953d0f048cdc9c9d75408c95288d608cf2fd254d035323550d0c849d18c5508f152b031b13033354b06c2343b9022d71000fbd610170a656e6473747265616d0a656e646f626a0a2525454f460a",
        text: "48656c6c6f20576f72206c642048656c6c6f",
        title: "",
    },
    Fx {
        name: "plain_literal_tj_hex",
        max_chars: 2000000,
        input: "255044462d312e340a342030206f626a0a3c3c202f4c656e677468203633203e3e0a73747265616d0a4254202f4631203132205466202848656c6c6f2920546a205b28576f7229202d32353020286c64295d20544a203c343836353663366336663e20546a2045540a656e6473747265616d0a656e646f626a0a2525454f460a",
        text: "48656c6c6f20576f72206c642048656c6c6f",
        title: "",
    },
    Fx {
        name: "title_plus_flate",
        max_chars: 2000000,
        input: "255044462d312e340a312030206f626a0a3c3c202f5469746c6520284d7920504446205469746c6529202f417574686f7220286e6f626f647929203e3e0a656e646f626a0a342030206f626a0a3c3c202f466c6174654465636f6465202f4c656e677468203333203e3e0a73747265616d0a789c730a51d070ca4fa9542849ad2851c8482d4ad55408c952700d010065fb07d60a656e6473747265616d0a656e646f626a0a2525454f460a",
        text: "426f647920746578742068657265",
        title: "4d7920504446205469746c65",
    },
    Fx {
        name: "literal_escapes_octal",
        max_chars: 2000000,
        input: "255044462d312e340a342030206f626a0a3c3c202f4c656e677468203236203e3e0a73747265616d0a42542028415c74425c3130315c6e5c28785c292920546a2045540a656e6473747265616d0a656e646f626a0a2525454f460a",
        text: "4120424120287829",
        title: "",
    },
    Fx {
        name: "title_escapes_octal",
        max_chars: 2000000,
        input: "255044462d312e340a312030206f626a0a3c3c202f5469746c6520284361665c3335315c5c205c28785c2929203e3e0a656e646f626a0a342030206f626a0a3c3c202f4c656e677468203132203e3e0a73747265616d0a42542028782920546a2045540a656e6473747265616d0a656e646f626a0a2525454f460a",
        text: "78",
        title: "436166c3a95c20287829",
    },
    Fx {
        name: "title_hex_unsupported",
        max_chars: 2000000,
        input: "255044462d312e340a312030206f626a0a3c3c202f5469746c65203c3444373932303534363937343e203e3e0a656e646f626a0a342030206f626a0a3c3c202f4c656e677468203139203e3e0a73747265616d0a4254202868617320626f64792920546a2045540a656e6473747265616d0a656e646f626a0a2525454f460a",
        text: "68617320626f6479",
        title: "",
    },
    Fx {
        name: "hex_odd_and_nested_parens",
        max_chars: 2000000,
        input: "255044462d312e340a342030206f626a0a3c3c202f4c656e677468203430203e3e0a73747265616d0a4254203c343820363520366320366320363e20546a20286f757428696e296f75742920546a2045540a656e6473747265616d0a656e646f626a0a2525454f460a",
        text: "48656c6c60206f757428696e296f7574",
        title: "",
    },
    Fx {
        name: "pdf_no_streams",
        max_chars: 2000000,
        input: "255044462d312e340a6e6f7468696e6720746f2073656520686572650a2525454f460a",
        text: "",
        title: "",
    },
    Fx {
        name: "stream_without_operators",
        max_chars: 2000000,
        input: "255044462d312e340a342030206f626a0a3c3c202f4c656e677468203230203e3e0a73747265616d0a72617720646174612c206e6164612c20686572650a656e6473747265616d0a656e646f626a0a2525454f460a",
        text: "",
        title: "",
    },
    Fx {
        name: "max_chars_truncation",
        max_chars: 4,
        input: "255044462d312e340a342030206f626a0a3c3c202f4c656e677468203231203e3e0a73747265616d0a425420286162636465666768696a2920546a2045540a656e6473747265616d0a656e646f626a0a2525454f460a",
        text: "61626364",
        title: "",
    },
    Fx {
        name: "empty_input",
        max_chars: 2000000,
        input: "",
        text: "",
        title: "",
    },
    Fx {
        name: "garbage_no_pdf_marker",
        max_chars: 2000000,
        input: "6e6f742061207064662c206a757374206279746573",
        text: "",
        title: "",
    },
];

#[test]
fn pdftext_matches_python() {
    for fx in FIXTURES {
        let input = unhex(fx.input);
        let want_text = String::from_utf8(unhex(fx.text)).unwrap();
        let got_text = websearch::pdftext::extract_text(&input, fx.max_chars);
        assert_eq!(got_text, want_text, "extract_text mismatch: {}", fx.name);
        let want_title = String::from_utf8(unhex(fx.title)).unwrap();
        let got_title = websearch::pdftext::extract_title(&input);
        assert_eq!(got_title, want_title, "extract_title mismatch: {}", fx.name);
    }
}
