//! `gitweb` — a read-only, no-JavaScript git web frontend.
//!
//! Browse repositories, logs, commits/diffs, trees, blobs, blame, refs, tags and
//! releases, plus a read-only patch/mail archive (the Sourcehut collaboration
//! model — the write path lives entirely outside this service). Every page is a
//! complete server-rendered HTML document; no JavaScript is emitted anywhere.
//!
//! **The safety property, as a rule the type system helps keep:** every call to
//! `git` is an **argv vector** handed to `std::process::Command` — never a shell
//! string — so a branch, path or ref containing shell metacharacters can never
//! become a command. Repository paths are confined to the configured root, and
//! every dynamic value is escaped at render time.
//!
//! A port of the Python `gitweb`. The plumbing and rendering tiers compile with
//! **zero third-party dependencies** (execing `git` needs only `std::process`);
//! the HTTP server lives behind the opt-in `net` feature.
//!
//! # Feature tiers
//!
//! Mirrors the other engines: every module below builds under the default
//! (empty) feature set with zero third-party dependencies — including all of
//! [`views`] and the whole request→response mapping in [`server`]; live
//! networking (the accept loop and the `gitweb` binary) is opt-in behind
//! `net`/`rand`.
//!
//! # The tiers
//!
//! * [`markup`] — escaping, dates, the minimal Markdown subset, unified-diff
//!   parsing.
//! * [`gitcmd`] — the read-only `git` plumbing: argv-only exec, root
//!   confinement as a type, and every output parser.
//! * [`views`] — pure functions returning complete HTML/XML documents.
//! * [`server`] — a pure [`Route`]/[`Resp`] mapping over a [`Server`], plus the
//!   `net`-gated accept loop.
//! * [`auth`] (optional HTTP Basic access control), [`metrics`] (the
//!   request-counter registry) and [`mailarchive`] (the read-only mbox/patch
//!   archive).
//!
//! Every pure tier is cross-checked **byte-identical** to the Python reference
//! in `tests/xcheck_*.rs`, with the goldens regenerated by
//! `tests/regen_goldens.py`, `tests/regen_gitcmd_goldens.py` and
//! `tests/regen_views_goldens.py`; the serving contract is asserted without a
//! socket in `tests/route_server.rs` and over loopback (including a real
//! `git clone`) in `tests/net_server.rs`.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

pub mod auth;
pub mod gitcmd;
pub mod mailarchive;
pub mod markup;
pub mod metrics;
pub mod server;
pub mod views;

// The command line, shared by the standalone `gitweb` binary and by
// `astrx gitweb …`. Behind `net` because every runnable subcommand ends in a
// socket, matching the `[[bin]]` `required-features` — the default build stays a
// pure, zero-dependency library.
#[cfg(feature = "net")]
pub mod cli;

mod deflate;
mod pycompat;

pub use auth::{
    check_basic_auth, hash_password, parse_auth_spec, verify_password, AuthSpecError, Credential,
};
pub use gitcmd::{
    blame, blob_size, branches, cached_last_commit_ts, close_catfiles, commit_count,
    commit_count_grep, commit_count_path, commit_meta, commit_patch, compare, decode_output,
    default_branch, discover_repos, for_each_ref, format_patch, is_allowed_subcommand, is_binary,
    lfs_object_path, lfs_object_size, list_tree, log, log_graph, log_grep, log_path, object_spec,
    object_type, parse_batch_header, parse_blame, parse_commit_record, parse_gitmodules,
    parse_graph_records, parse_grep_matches, parse_lfs_pointer, parse_log_records,
    parse_ref_records, parse_tree_entries, peek_blob, peek_file, read_blob, read_file,
    read_gitmodules, ref_exists, ref_names, resolve_commit, resolve_repo, run_git, search_code,
    stat_object, stream_archive, stream_blob, stream_file, tags, upload_pack_advertise,
    upload_pack_rpc, valid_path, valid_query, valid_ref, valid_repo_name, BlameLine, BlobRead,
    Commit, CommitRow, FileStream, GitCatFile, GitError, GitOutput, GitStream, GraphCommit,
    GrepMatch, LfsPointer, ObjStat, RefKind, RefPattern, RefRow, Repo, RepoName, RepoPath,
    RunOptions, SafePath, SafeQuery, SafeRef, TreeEntry, ALLOWED_SUBCOMMANDS, DEFAULT_MAX_BYTES,
    DEFAULT_TIMEOUT, FIELD_SEP, GREP_MAX_MATCHES, MAX_QUERY_BYTES,
};
pub use mailarchive::{
    group_threads, normalize_subject, parse_mbox, read_archive, render_list, render_thread,
    thread_id, thread_mbox, Msg, Thread, MAX_BODY, MAX_MESSAGES, PATCH_CSS,
};
pub use markup::{
    atom_date, esc, iso_date, parse_patch, relative_date, render_markdown, render_readme,
    xml_escape, DiffFile, DiffKind, DiffLine, FileStatus, MAX_MARKDOWN_BYTES,
};
pub use metrics::{registry, Metrics, Snapshot};
pub use server::{
    make_etag, negotiate_encoding, normalize_prefix, reason, Action, Body, ByteStream, Config,
    Request, Resp, Route, Routed, Server, CSP, MAX_REQUEST_HEAD, RENDER_VERSION,
};
#[cfg(feature = "net")]
pub use server::{serve, serve_config};
pub use views::{
    assign_lanes, atom_feed, blame_page, blob_page, commit_page, compare_page, error_page,
    graph_page, history_page, log_page, numbered_lines, opensearch_repo, opensearch_site, page,
    ref_switcher, refs, releases, releases_atom, repo_list, search_page, signature_badge,
    signature_detail, summary, tree_page, BlobView, Ctx, HistoryView, LaneNode, Readme, RefChoices,
    SearchView, TreeView, CSS,
};
