//! Server-rendered HTML views. **No JavaScript is emitted anywhere.**
//!
//! Every view is a pure function returning a complete HTML document (or, for the
//! feeds and the OpenSearch descriptors, a complete XML document) as a `String`.
//! All dynamic values pass through [`crate::markup::esc`] /
//! [`crate::markup::xml_escape`] (or the already-safe Markdown / diff renderers)
//! before they reach the output, so repository-controlled text — a branch name, a
//! filename, a commit subject — can never inject markup.
//!
//! A faithful port of the Python `gitweb.views`, cross-checked byte-identical
//! against the reference in `tests/xcheck_views.rs` (goldens regenerated by
//! `tests/regen_views_goldens.py`).
//!
//! # Purity
//!
//! The module has **zero** third-party dependencies and no network, filesystem
//! or clock access: the two pieces of ambient state the Python reference reads
//! from globals — the reverse-proxy mount prefix (a `ContextVar`) and the clock
//! [`crate::markup::relative_date`] compares against (`time.time()`) — are
//! carried explicitly in a [`Ctx`] the caller threads through. That is what makes
//! every view testable, and byte-comparable to Python, without a socket.
//!
//! # Documented divergence
//!
//! **Syntax highlighting is not ported.** In Python it is an optional Pygments
//! hook (`markup.highlight_source`) that returns `None` — falling back to escaped
//! plaintext — whenever Pygments is absent, which is always the case in the
//! zero-dependency deployment this crate targets (and is also the `Config`
//! default, `syntax_highlight = False`). [`numbered_lines`] therefore always
//! renders the escaped-plaintext form, byte-identical to the reference's default.

use crate::gitcmd::{
    BlameLine, Commit, CommitRow, GraphCommit, GrepMatch, LfsPointer, RefRow, Repo, TreeEntry,
};
use crate::markup::{atom_date, esc, relative_date, xml_escape, DiffFile};
use crawlcore::urlparse::{quote, urlencode};

// --------------------------------------------------------------------------- //
// Rendering context: the mount prefix + the clock
// --------------------------------------------------------------------------- //

/// The per-request rendering context every view is parameterised on.
///
/// It carries the two values the Python reference keeps in process-wide state:
///
/// * the **reverse-proxy mount prefix** (`--url-prefix`, e.g. `/git`) that every
///   generated URL is built on — Python holds it in a `ContextVar` set at the top
///   of each request so concurrent requests cannot cross-contaminate; passing it
///   explicitly makes that impossible by construction, and
/// * the **clock** [`relative_date`] measures against. `None` means "now", which
///   is what a live server uses; a fixed value makes a view's output a pure
///   function of its inputs, which is what the cross-check tests rely on.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Ctx {
    prefix: String,
    now: Option<f64>,
}

impl Ctx {
    /// A context mounted at `prefix` (`""` for the site root) using the live clock.
    #[must_use]
    pub fn new(prefix: &str) -> Self {
        Ctx {
            prefix: prefix.to_string(),
            now: None,
        }
    }

    /// A context mounted at `prefix` with `relative_date` pinned to `now`
    /// (epoch seconds) — deterministic rendering for tests and goldens.
    #[must_use]
    pub fn at(prefix: &str, now: f64) -> Self {
        Ctx {
            prefix: prefix.to_string(),
            now: Some(now),
        }
    }

    /// The reverse-proxy mount prefix (`""` when mounted at the site root).
    #[must_use]
    pub fn prefix(&self) -> &str {
        &self.prefix
    }

    /// The pinned clock, if any (`None` means "read the system clock").
    #[must_use]
    pub fn now(&self) -> Option<f64> {
        self.now
    }

    /// The repository-list URL — Python `u_home()`.
    #[must_use]
    pub fn home(&self) -> String {
        format!("{}/", self.prefix)
    }

    /// A repository's summary URL — Python `u_repo(name)`.
    #[must_use]
    pub fn repo(&self, name: &str) -> String {
        format!("{}/{}/", self.prefix, quote(name, ""))
    }

    /// An action URL with a query string — Python `u_action(name, action, **params)`.
    ///
    /// Parameters whose value is empty are dropped (Python drops `None` and `""`),
    /// and the rest are `urlencode`d in the order given.
    #[must_use]
    pub fn action(&self, name: &str, action: &str, params: &[(&str, &str)]) -> String {
        let mut base = format!("{}/{}/{action}", self.prefix, quote(name, ""));
        let clean: Vec<(String, String)> = params
            .iter()
            .filter(|(_, v)| !v.is_empty())
            .map(|(k, v)| ((*k).to_string(), (*v).to_string()))
            .collect();
        if !clean.is_empty() {
            base.push('?');
            base.push_str(&urlencode(&clean));
        }
        base
    }

    /// `relative_date(ts)` against this context's clock.
    fn rel(&self, ts: Option<i64>) -> String {
        relative_date(ts, self.now)
    }
}

/// Return an escaped `href` for an http(s) URL, else `None` (not linkable).
fn safe_external(url: &str) -> Option<String> {
    let probe = url.trim();
    let low = probe.to_lowercase();
    if low.starts_with("https://") || low.starts_with("http://") {
        Some(esc(probe))
    } else {
        None
    }
}

// --------------------------------------------------------------------------- //
// Styling (inline, no external assets, no JS)
// --------------------------------------------------------------------------- //

/// The single inline stylesheet every page carries. No external assets, no JS.
pub const CSS: &str = "
:root{--fg:#1f2328;--muted:#656d76;--bg:#ffffff;--soft:#f6f8fa;
--border:#d0d7de;--link:#0969da;--add-bg:#e6ffec;--add-br:#a6f0b8;
--del-bg:#ffebe9;--del-br:#f7c4c0;--hunk:#57606a;--hunk-bg:#eef4ff;}
*{box-sizing:border-box}
body{margin:0;color:var(--fg);background:var(--bg);
font:14px/1.5 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif}
a{color:var(--link);text-decoration:none}
a:hover{text-decoration:underline}
code,pre,.mono,td.line,td.diff-line{font-family:ui-monospace,SFMono-Regular,
Menlo,Consolas,monospace}
.wrap{max-width:1080px;margin:0 auto;padding:0 16px 48px}
header.top{background:var(--soft);border-bottom:1px solid var(--border);
padding:10px 0;margin-bottom:20px}
header.top .wrap{padding-top:0;padding-bottom:0}
header.top a.brand{font-weight:700;font-size:16px;color:var(--fg)}
.repo-head{display:flex;align-items:baseline;gap:10px;flex-wrap:wrap;
margin:6px 0 2px}
.repo-head h1{font-size:20px;margin:0}
.desc{color:var(--muted);margin:2px 0 12px}
nav.tabs{border-bottom:1px solid var(--border);margin:0 0 18px;
display:flex;gap:4px;flex-wrap:wrap}
nav.tabs a{padding:6px 12px;border:1px solid transparent;border-bottom:none;
border-radius:6px 6px 0 0;color:var(--muted)}
nav.tabs a.active{color:var(--fg);border-color:var(--border);
background:var(--bg);position:relative;top:1px}
table{border-collapse:collapse;width:100%}
table.list td,table.list th{padding:8px 10px;border-bottom:1px solid var(--border);
text-align:left;vertical-align:top}
table.list th{color:var(--muted);font-weight:600;font-size:12px;
text-transform:uppercase;letter-spacing:.03em}
tr:hover td{background:var(--soft)}
.muted{color:var(--muted)}
.mono{font-size:12.5px}
.sha{color:var(--muted)}
.pill{display:inline-block;padding:0 7px;border:1px solid var(--border);
border-radius:999px;font-size:12px;color:var(--muted);background:var(--soft)}
.crumbs{margin:0 0 12px;font-size:13px}
.box{border:1px solid var(--border);border-radius:6px;overflow:hidden;
margin:0 0 20px}
.box .box-head{background:var(--soft);border-bottom:1px solid var(--border);
padding:8px 12px;font-weight:600}
.box .box-body{padding:16px}
.readme :first-child{margin-top:0}
.readme pre{background:var(--soft);padding:12px;border-radius:6px;overflow:auto}
.readme code{background:var(--soft);padding:.1em .3em;border-radius:4px}
.readme pre code{background:none;padding:0}
.readme blockquote{margin:0;padding:0 12px;color:var(--muted);
border-left:3px solid var(--border)}
.readme h1,.readme h2{border-bottom:1px solid var(--border);padding-bottom:.2em}
.readme table.md-table{border-collapse:collapse;margin:0 0 12px}
.readme table.md-table th,.readme table.md-table td{border:1px solid var(--border);
padding:6px 12px}
.readme table.md-table th{background:var(--soft)}
.readme li.task{list-style:none;margin-left:-1.2em}
.readme li.task input{margin-right:.4em}
.readme img{max-width:100%}
/* blob + blame line tables */
table.code{border:1px solid var(--border);border-radius:6px;overflow:hidden}
table.code td{padding:0 10px;vertical-align:top;white-space:pre;
font-size:12.5px;line-height:1.45}
td.lineno{width:1%;text-align:right;color:var(--muted);
background:var(--soft);border-right:1px solid var(--border);
user-select:none;-webkit-user-select:none}
td.lineno a{color:var(--muted)}
td.line{width:100%}
td.b-sha{background:var(--soft);border-right:1px solid var(--border);
white-space:nowrap}
td.b-auth{color:var(--muted);border-right:1px solid var(--border);
white-space:nowrap;max-width:160px;overflow:hidden;text-overflow:ellipsis}
/* diff */
.file{border:1px solid var(--border);border-radius:6px;overflow:hidden;
margin:0 0 16px}
.file-head{background:var(--soft);border-bottom:1px solid var(--border);
padding:8px 12px;display:flex;gap:10px;align-items:center;flex-wrap:wrap}
.file-head .path{font-family:ui-monospace,monospace;font-size:13px}
.stat-add{color:#1a7f37;font-weight:600}
.stat-del{color:#cf222e;font-weight:600}
table.diff{width:100%}
table.diff td{padding:0 12px;white-space:pre;font-size:12.5px;line-height:1.45}
tr.diff-add td{background:var(--add-bg)}
tr.diff-del td{background:var(--del-bg)}
tr.diff-hunk td{background:var(--hunk-bg);color:var(--hunk)}
tr.diff-add:hover td,tr.diff-del:hover td,tr.diff-hunk:hover td{filter:none}
.pager{display:flex;gap:10px;margin:16px 0;align-items:center}
.pager a,.pager span{padding:5px 12px;border:1px solid var(--border);
border-radius:6px}
.pager span.disabled{color:var(--muted);background:var(--soft)}
footer{color:var(--muted);font-size:12px;border-top:1px solid var(--border);
margin-top:32px;padding-top:12px}
.warn{background:#fff8c5;border:1px solid #eac54f;border-radius:6px;
padding:10px 12px;margin:0 0 16px}
img.blob-img{max-width:100%;height:auto;background:var(--soft);
border:1px solid var(--border)}
.badge-ok{display:inline-block;padding:0 8px;border-radius:999px;font-size:12px;
color:#0f5132;background:#d1e7dd;border:1px solid #a3cfbb}
.badge-warn{display:inline-block;padding:0 8px;border-radius:999px;font-size:12px;
color:#842029;background:#f8d7da;border:1px solid #f1aeb5}
tr.hl td,tr:target td{background:#fff8c5}
details.switch{margin:0 0 12px}
details.switch summary{cursor:pointer;display:inline-block;padding:5px 12px;
border:1px solid var(--border);border-radius:6px;background:var(--soft)}
details.switch .menu{border:1px solid var(--border);border-radius:6px;
margin-top:6px;padding:8px 12px;max-height:280px;overflow:auto}
details.switch .menu a{display:inline-block;margin:2px 8px 2px 0}
pre.clone-cmd{background:var(--soft);border:1px solid var(--border);
border-radius:6px;padding:10px 12px;margin:0;overflow:auto;font-size:12.5px}
form.search{display:flex;gap:8px;margin:0 0 16px;flex-wrap:wrap;align-items:center}
form.search input[type=search]{flex:1 1 220px;min-width:160px;padding:6px 10px;
border:1px solid var(--border);border-radius:6px;font:inherit}
form.search select,form.search button{padding:6px 12px;border:1px solid var(--border);
border-radius:6px;background:var(--soft);font:inherit;cursor:pointer}
.search-file{margin:0 0 16px}
.search-file .box-head{font-family:ui-monospace,monospace;font-size:13px}
table.grep td.line{white-space:pre-wrap;word-break:break-word}
/* commit graph */
.graph-wrap{display:flex;align-items:flex-start;border:1px solid var(--border);
border-radius:6px;overflow:auto;margin:0 0 16px}
svg.graph-svg{flex:none;display:block;background:var(--bg)}
.graph-rows{flex:1;min-width:0}
.graph-row{height:24px;line-height:24px;padding:0 10px;white-space:nowrap;
overflow:hidden;text-overflow:ellipsis;border-bottom:1px solid var(--border)}
.graph-row:last-child{border-bottom:none}
.graph-row:hover{background:var(--soft)}
";

// --------------------------------------------------------------------------- //
// Document shell
// --------------------------------------------------------------------------- //

/// The per-repository tab strip, with `active` highlighted.
fn tabs(ctx: &Ctx, repo_name: &str, active: &str) -> String {
    let items: [(&str, &str, String); 8] = [
        ("summary", "Summary", ctx.repo(repo_name)),
        ("refs", "Refs", ctx.action(repo_name, "refs", &[])),
        ("log", "Log", ctx.action(repo_name, "log", &[])),
        ("graph", "Graph", ctx.action(repo_name, "graph", &[])),
        ("tree", "Tree", ctx.action(repo_name, "tree", &[])),
        (
            "releases",
            "Releases",
            ctx.action(repo_name, "releases", &[]),
        ),
        ("patches", "Patches", ctx.action(repo_name, "patches", &[])),
        ("search", "Search", ctx.action(repo_name, "search", &[])),
    ];
    let mut out = String::from("<nav class=\"tabs\">");
    for (key, label, url) in &items {
        let cls = if *key == active {
            " class=\"active\""
        } else {
            ""
        };
        out.push_str(&format!("<a{cls} href=\"{}\">{}</a>", esc(url), esc(label)));
    }
    out.push_str("</nav>");
    out
}

/// Wrap `body` in the full HTML document (head, header, tabs, footer).
///
/// `repo_name` selects the repository chrome (title link, description, tab
/// strip, Atom + per-repo OpenSearch autodiscovery); `None` renders the bare
/// site shell used by the repository list and the error pages.
#[must_use]
pub fn page(
    ctx: &Ctx,
    title: &str,
    body: &str,
    repo_name: Option<&str>,
    active_tab: &str,
    repo_desc: &str,
) -> String {
    let mut out = String::with_capacity(CSS.len() + body.len() + 2048);
    out.push_str("<!doctype html>");
    out.push_str("<html lang=\"en\"><head><meta charset=\"utf-8\">");
    out.push_str("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">");
    out.push_str("<meta name=\"referrer\" content=\"no-referrer\">");
    out.push_str(&format!("<title>{}</title>", esc(title)));
    out.push_str(&format!("<style>{CSS}</style>"));
    // Autodiscovery links, in the order the reference's `head.insert(6, …)`
    // calls leave them: the per-repo code-search descriptor, then the repo's
    // Atom feed, then the site-level (repository finder) descriptor.
    if let Some(name) = repo_name {
        let os_href = format!("{}/{}/opensearch.xml", ctx.prefix(), quote(name, ""));
        out.push_str(&format!(
            "<link rel=\"search\" type=\"application/opensearchdescription+xml\" \
             title=\"{} code\" href=\"{}\">",
            esc(name),
            esc(&os_href)
        ));
        out.push_str(&format!(
            "<link rel=\"alternate\" type=\"application/atom+xml\" \
             title=\"{} commits\" href=\"{}\">",
            esc(name),
            esc(&ctx.action(name, "atom", &[]))
        ));
    }
    out.push_str(&format!(
        "<link rel=\"search\" type=\"application/opensearchdescription+xml\" \
         title=\"gitweb repositories\" href=\"{}\">",
        esc(&format!("{}/opensearch.xml", ctx.prefix()))
    ));
    out.push_str("</head><body>");
    out.push_str("<header class=\"top\"><div class=\"wrap\">");
    out.push_str(&format!(
        "<a class=\"brand\" href=\"{}\">gitweb</a>",
        esc(&ctx.home())
    ));
    out.push_str("</div></header>");
    out.push_str("<div class=\"wrap\">");
    if let Some(name) = repo_name {
        out.push_str("<div class=\"repo-head\">");
        out.push_str(&format!(
            "<h1><a href=\"{}\">{}</a></h1>",
            esc(&ctx.repo(name)),
            esc(name)
        ));
        out.push_str("</div>");
        if !repo_desc.is_empty() {
            out.push_str(&format!("<div class=\"desc\">{}</div>", esc(repo_desc)));
        }
        out.push_str(&tabs(ctx, name, active_tab));
    }
    out.push_str(body);
    out.push_str(
        "<footer>Served by gitweb — a read-only, no-JavaScript git viewer.\
         </footer></div></body></html>",
    );
    out
}

/// The error page shown for every 4xx/5xx that renders HTML.
#[must_use]
pub fn error_page(ctx: &Ctx, code: u16, message: &str) -> String {
    let body = format!(
        "<div class=\"box\"><div class=\"box-head\">Error {code}</div>\
         <div class=\"box-body\"><p>{}</p>\
         <p><a href=\"{}\">&larr; Back to repositories</a></p>\
         </div></div>",
        esc(message),
        esc(&ctx.home())
    );
    page(ctx, &format!("Error {code}"), &body, None, "", "")
}

// --------------------------------------------------------------------------- //
// Repo list
// --------------------------------------------------------------------------- //

/// The repository index: a no-JS name/description filter over the discovered repos.
#[must_use]
pub fn repo_list(ctx: &Ctx, repos: &[Repo], q: &str) -> String {
    let mut rows = String::new();
    for r in repos {
        let when = match r.last_commit_ts {
            Some(ts) if ts != 0 => ctx.rel(Some(ts)),
            _ => "empty".to_string(),
        };
        let kind = if r.bare { "bare" } else { "worktree" };
        let desc = esc(&r.description);
        rows.push_str(&format!(
            "<tr><td><a href=\"{}\">{}</a> <span class=\"pill\">{}</span></td>\
             <td class=\"muted\">{}</td><td class=\"muted\">{}</td></tr>",
            esc(&ctx.repo(&r.name)),
            esc(&r.name),
            esc(kind),
            if desc.is_empty() { "&mdash;" } else { &desc },
            esc(&when),
        ));
    }
    let table = if rows.is_empty() {
        let empty = if q.is_empty() {
            "No repositories found under the configured root."
        } else {
            "No repositories match that filter."
        };
        format!("<p class=\"muted\">{}</p>", esc(empty))
    } else {
        format!(
            "<table class=\"list\"><thead><tr><th>Repository</th>\
             <th>Description</th><th>Last commit</th></tr></thead><tbody>{rows}</tbody></table>"
        )
    };
    // A no-JS repository finder (form-action 'self'). Submitting filters the
    // list by name/description; this is also the target of the site-level
    // OpenSearch descriptor, so a browser can jump to a repo from the URL bar.
    let form = format!(
        "<form class=\"search\" method=\"get\" action=\"{}\" role=\"search\">\
         <input type=\"search\" name=\"q\" value=\"{}\" \
         placeholder=\"Filter repositories…\" aria-label=\"Filter repositories\">\
         <button type=\"submit\">Filter</button></form>",
        esc(&ctx.home()),
        esc(q)
    );
    let body = format!(
        "<div class=\"repo-head\"><h1>Repositories</h1></div>\
         <div class=\"desc\">Read-only browser</div>{form}{table}"
    );
    page(ctx, "Repositories", &body, None, "", "")
}

// --------------------------------------------------------------------------- //
// Summary
// --------------------------------------------------------------------------- //

/// The `<tr>` rows shared by every commit listing.
fn commit_rows(ctx: &Ctx, repo_name: &str, rows: &[CommitRow]) -> String {
    let mut out = String::new();
    for c in rows {
        let url = ctx.action(repo_name, "commit", &[("id", &c.sha)]);
        out.push_str(&format!(
            "<tr><td class=\"mono\"><a href=\"{}\">{}</a></td>\
             <td>{}</td><td class=\"muted\">{}</td><td class=\"muted\">{}</td></tr>",
            esc(&url),
            esc(&c.short),
            esc(&c.subject),
            esc(&c.author),
            esc(&ctx.rel(Some(c.ts))),
        ));
    }
    out
}

/// The repository summary: default branch, clone command, latest commits, README.
#[must_use]
pub fn summary(
    ctx: &Ctx,
    repo: &Repo,
    branch: &str,
    commits: &[CommitRow],
    readme: &Readme<'_>,
    clone_url: Option<&str>,
) -> String {
    let mut parts = String::new();
    parts.push_str(
        "<div class=\"box\"><div class=\"box-head\">Overview</div><div class=\"box-body\">",
    );
    parts.push_str(&format!(
        "<p>Default branch: <span class=\"pill\">{}</span></p>",
        esc(branch)
    ));
    parts.push_str(&format!(
        "<p><a href=\"{}\">Browse commit log</a> &middot; \
         <a href=\"{}\">Browse files</a> &middot; \
         <a href=\"{}\">Branches &amp; tags</a></p>",
        esc(&ctx.action(&repo.name, "log", &[("ref", branch)])),
        esc(&ctx.action(&repo.name, "tree", &[("ref", branch)])),
        esc(&ctx.action(&repo.name, "refs", &[])),
    ));
    parts.push_str("</div></div>");
    if let Some(url) = clone_url.filter(|u| !u.is_empty()) {
        // Read-only clone transport (Git Smart HTTP). The URL is fully escaped.
        parts.push_str(&format!(
            "<div class=\"box\"><div class=\"box-head\">Clone (read-only)</div>\
             <div class=\"box-body\"><pre class=\"clone-cmd\">git clone {}</pre></div></div>",
            esc(url)
        ));
    }
    if !commits.is_empty() {
        parts.push_str(&format!(
            "<div class=\"box\"><div class=\"box-head\">Latest commits</div>\
             <table class=\"list\"><tbody>{}</tbody></table></div>",
            commit_rows(ctx, &repo.name, commits)
        ));
    }
    if let Some(html) = readme.html {
        parts.push_str(&format!(
            "<div class=\"box\"><div class=\"box-head\">{}</div>\
             <div class=\"box-body readme\">{html}</div></div>",
            esc(readme.name.unwrap_or("README"))
        ));
    }
    page(
        ctx,
        &repo.name,
        &parts,
        Some(&repo.name),
        "summary",
        &repo.description,
    )
}

// --------------------------------------------------------------------------- //
// Refs / releases
// --------------------------------------------------------------------------- //

fn ref_box(ctx: &Ctx, repo: &Repo, rows: &[RefRow], title: &str) -> String {
    let mut body = String::new();
    for r in rows {
        body.push_str(&format!(
            "<tr><td><a href=\"{}\">{}</a></td>\
             <td class=\"mono\"><a href=\"{}\">{}</a></td>\
             <td>{}</td><td class=\"muted\">{}</td><td><a href=\"{}\">tree</a></td></tr>",
            esc(&ctx.action(&repo.name, "log", &[("ref", &r.name)])),
            esc(&r.name),
            esc(&ctx.action(&repo.name, "commit", &[("id", &r.target)])),
            esc(&r.target),
            esc(&r.subject),
            esc(&ctx.rel(Some(r.ts))),
            esc(&ctx.action(&repo.name, "tree", &[("ref", &r.name)])),
        ));
    }
    let inner = if body.is_empty() {
        format!(
            "<div class=\"box-body muted\">No {}.</div>",
            esc(&title.to_lowercase())
        )
    } else {
        format!(
            "<table class=\"list\"><thead><tr><th>Name</th><th>Commit</th>\
             <th>Subject</th><th>Updated</th><th></th></tr></thead><tbody>{body}</tbody></table>"
        )
    };
    format!(
        "<div class=\"box\"><div class=\"box-head\">{}</div>{inner}</div>",
        esc(title)
    )
}

/// Branches and tags, each linking to its log, tip commit and tree.
#[must_use]
pub fn refs(ctx: &Ctx, repo: &Repo, branch_rows: &[RefRow], tag_rows: &[RefRow]) -> String {
    let body = ref_box(ctx, repo, branch_rows, "Branches") + &ref_box(ctx, repo, tag_rows, "Tags");
    page(
        ctx,
        &format!("{}: refs", repo.name),
        &body,
        Some(&repo.name),
        "refs",
        &repo.description,
    )
}

/// A release list built from tags (newest first): notes, date, commit and a
/// source snapshot download per tag, plus an Atom feed for release watchers.
#[must_use]
pub fn releases(ctx: &Ctx, repo: &Repo, tag_rows: &[RefRow]) -> String {
    let mut rows = String::new();
    for r in tag_rows {
        rows.push_str(&format!(
            "<tr><td><strong>{}</strong></td><td>{}</td><td class=\"muted\">{}</td>\
             <td class=\"mono\"><a href=\"{}\">{}</a></td>\
             <td><a href=\"{}\">tar.gz</a> &middot; <a href=\"{}\">browse</a></td></tr>",
            esc(&r.name),
            esc(&r.subject),
            esc(&ctx.rel(Some(r.ts))),
            esc(&ctx.action(&repo.name, "commit", &[("id", &r.target)])),
            esc(&r.target),
            esc(&ctx.action(&repo.name, "archive", &[("ref", &r.name)])),
            esc(&ctx.action(&repo.name, "tree", &[("ref", &r.name)])),
        ));
    }
    let inner = if rows.is_empty() {
        "<div class=\"box-body muted\">No releases yet. Tag a commit \
         (<code>git tag -a v1.0</code>) to publish one.</div>"
            .to_string()
    } else {
        format!(
            "<table class=\"list\"><thead><tr><th>Tag</th><th>Notes</th>\
             <th>Date</th><th>Commit</th><th>Download</th></tr></thead><tbody>{rows}</tbody></table>"
        )
    };
    let feed = ctx.action(&repo.name, "releases.atom", &[]);
    let body = format!(
        "<div class=\"box\"><div class=\"box-head\">Releases \
         <a class=\"muted\" href=\"{}\" style=\"float:right\">Atom</a></div>{inner}</div>",
        esc(&feed)
    );
    page(
        ctx,
        &format!("{}: releases", repo.name),
        &body,
        Some(&repo.name),
        "releases",
        &repo.description,
    )
}

/// Atom 1.0 feed of releases (tags).
///
/// Every field is XML-escaped (dropping XML-illegal control characters) so one
/// hostile tag name can't break the feed.
#[must_use]
pub fn releases_atom(ctx: &Ctx, repo: &Repo, tag_rows: &[RefRow], base_url: &str) -> String {
    let abs = |rel: &str| -> String {
        if base_url.is_empty() {
            rel.to_string()
        } else {
            format!("{base_url}{rel}")
        }
    };
    let self_link = abs(&ctx.action(&repo.name, "releases.atom", &[]));
    let repo_link = abs(&ctx.repo(&repo.name));
    let updated = atom_date(tag_rows.first().map(|r| r.ts));
    let feed_id = if self_link.is_empty() {
        format!("urn:gitweb:{}:releases", repo.name)
    } else {
        self_link.clone()
    };
    let mut out = String::new();
    out.push_str("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
    out.push_str("<feed xmlns=\"http://www.w3.org/2005/Atom\">");
    out.push_str(&format!(
        "<title>{}: releases</title>",
        xml_escape(&repo.name)
    ));
    out.push_str(&format!("<id>{}</id>", xml_escape(&feed_id)));
    out.push_str(&format!("<updated>{}</updated>", xml_escape(&updated)));
    out.push_str(&format!(
        "<link rel=\"self\" href=\"{}\"/>",
        xml_escape(&self_link)
    ));
    out.push_str(&format!(
        "<link rel=\"alternate\" href=\"{}\"/>",
        xml_escape(&repo_link)
    ));
    out.push_str("<generator>gitweb</generator>");
    for r in tag_rows {
        let entry_link = abs(&ctx.action(&repo.name, "archive", &[("ref", &r.name)]));
        out.push_str("<entry>");
        out.push_str(&format!("<title>{}</title>", xml_escape(&r.name)));
        out.push_str(&format!(
            "<id>urn:gitweb:release:{}:{}</id>",
            xml_escape(&repo.name),
            xml_escape(&r.name)
        ));
        out.push_str(&format!(
            "<updated>{}</updated>",
            xml_escape(&atom_date(Some(r.ts)))
        ));
        out.push_str(&format!(
            "<link rel=\"alternate\" href=\"{}\"/>",
            xml_escape(&entry_link)
        ));
        out.push_str(&format!(
            "<author><name>{}</name></author>",
            xml_escape(&r.author)
        ));
        out.push_str(&format!(
            "<summary type=\"text\">{}</summary>",
            xml_escape(&r.subject)
        ));
        out.push_str("</entry>");
    }
    out.push_str("</feed>");
    out
}

// --------------------------------------------------------------------------- //
// Log
// --------------------------------------------------------------------------- //

/// A paginated commit log for one ref.
#[must_use]
pub fn log_page(
    ctx: &Ctx,
    repo: &Repo,
    reference: &str,
    rows: &[CommitRow],
    page_num: usize,
    total_pages: usize,
) -> String {
    let header = format!(
        "<p class=\"muted\">Log for <span class=\"pill\">{}</span> \
         &mdash; page {page_num} of {}</p>",
        esc(reference),
        total_pages.max(1)
    );
    let table = if rows.is_empty() {
        "<p class=\"muted\">No commits.</p>".to_string()
    } else {
        format!(
            "<table class=\"list\"><thead><tr><th>Commit</th><th>Subject</th>\
             <th>Author</th><th>When</th></tr></thead><tbody>{}</tbody></table>",
            commit_rows(ctx, &repo.name, rows)
        )
    };
    let mut pager = String::from("<div class=\"pager\">");
    if page_num > 1 {
        let prev = ctx.action(
            &repo.name,
            "log",
            &[("ref", reference), ("page", &(page_num - 1).to_string())],
        );
        pager.push_str(&format!("<a href=\"{}\">&larr; Newer</a>", esc(&prev)));
    } else {
        pager.push_str("<span class=\"disabled\">&larr; Newer</span>");
    }
    if page_num < total_pages {
        let next = ctx.action(
            &repo.name,
            "log",
            &[("ref", reference), ("page", &(page_num + 1).to_string())],
        );
        pager.push_str(&format!("<a href=\"{}\">Older &rarr;</a>", esc(&next)));
    } else {
        pager.push_str("<span class=\"disabled\">Older &rarr;</span>");
    }
    pager.push_str("</div>");
    page(
        ctx,
        &format!("{}: log", repo.name),
        &(header + &table + &pager),
        Some(&repo.name),
        "log",
        &repo.description,
    )
}

// --------------------------------------------------------------------------- //
// Commit
// --------------------------------------------------------------------------- //

/// Render a parsed unified diff (one `.file` block per file).
fn render_diff(files: &[DiffFile]) -> String {
    let mut out = String::new();
    for f in files {
        out.push_str(&format!(
            "<div class=\"file\"><div class=\"file-head\">\
             <span class=\"path\">{}</span><span class=\"pill\">{}</span>\
             <span class=\"stat-add\">+{}</span><span class=\"stat-del\">-{}</span></div>",
            esc(&f.display_path()),
            esc(f.status.as_str()),
            f.additions,
            f.deletions,
        ));
        if f.binary {
            out.push_str("<div class=\"box-body muted\">Binary file not shown.</div>");
        } else if f.lines.is_empty() {
            out.push_str("<div class=\"box-body muted\">No textual changes.</div>");
        } else {
            out.push_str("<table class=\"diff\"><tbody>");
            for ln in &f.lines {
                out.push_str(&format!(
                    "<tr class=\"diff-{}\"><td class=\"diff-line\">{}</td></tr>",
                    esc(ln.kind.as_str()),
                    esc(&ln.text)
                ));
            }
            out.push_str("</tbody></table>");
        }
        out.push_str("</div>");
    }
    if out.is_empty() {
        return "<p class=\"muted\">No changes (empty or merge commit).</p>".to_string();
    }
    out
}

/// git `%G?` status code → human label.
fn sig_label(status: &str) -> &'static str {
    match status {
        "G" => "good signature",
        "U" => "good signature, unknown validity",
        "X" => "good signature that has expired",
        "Y" => "good signature made by an expired key",
        "R" => "good signature made by a revoked key",
        "B" => "bad signature",
        "E" => "signature cannot be checked",
        _ => "signed",
    }
}

/// A small inline badge for the commit header (empty when unsigned).
#[must_use]
pub fn signature_badge(commit: &Commit) -> String {
    if commit.signature_verified() {
        return " <span class=\"badge-ok\" title=\"Verified signature\">Verified</span>"
            .to_string();
    }
    if commit.signature_present() {
        return " <span class=\"badge-warn\" title=\"Signature problem\">Unverified</span>"
            .to_string();
    }
    String::new()
}

/// The signature row shown in the commit metadata table.
#[must_use]
pub fn signature_detail(commit: &Commit) -> String {
    let label = sig_label(&commit.signature_status);
    let key = if commit.signing_key.is_empty() {
        String::new()
    } else {
        format!(" key {}", esc(&commit.signing_key))
    };
    if commit.signature_verified() {
        format!(
            "<span class=\"badge-ok\">Verified</span> &mdash; {}{key}",
            esc(label)
        )
    } else {
        format!("<span class=\"badge-warn\">{}</span>{key}", esc(label))
    }
}

/// One commit: metadata, signature state and the full diff.
#[must_use]
pub fn commit_page(ctx: &Ctx, repo: &Repo, commit: &Commit, files: &[DiffFile]) -> String {
    let parents: Vec<String> = commit
        .parents
        .iter()
        .map(|p| {
            format!(
                "<a class=\"mono\" href=\"{}\">{}</a>",
                esc(&ctx.action(&repo.name, "commit", &[("id", p)])),
                esc(&p.chars().take(8).collect::<String>())
            )
        })
        .collect();
    let parent_html = if parents.is_empty() {
        "<span class=\"muted\">none (root)</span>".to_string()
    } else {
        parents.join(", ")
    };
    let total_add: usize = files.iter().map(|f| f.additions).sum();
    let total_del: usize = files.iter().map(|f| f.deletions).sum();

    let mut meta = String::from("<div class=\"box\"><div class=\"box-head\">");
    meta.push_str(&format!(
        "{}{}</div><div class=\"box-body\">",
        esc(&commit.subject),
        signature_badge(commit)
    ));
    if !commit.body.is_empty() {
        meta.push_str(&format!("<pre>{}</pre>", esc(&commit.body)));
    }
    let sig_row = if commit.signature_present() {
        format!(
            "<tr><th>Signature</th><td>{}</td></tr>",
            signature_detail(commit)
        )
    } else {
        String::new()
    };
    meta.push_str(&format!(
        "<table class=\"list\"><tbody>\
         <tr><th>Commit</th><td class=\"mono\">{sha}</td></tr>\
         <tr><th>Author</th><td>{an} &lt;{ae}&gt; <span class=\"muted\">{ad}</span></td></tr>\
         <tr><th>Committer</th><td>{cn} &lt;{ce}&gt; <span class=\"muted\">{cd}</span></td></tr>\
         {sig_row}\
         <tr><th>Parents</th><td>{parent_html}</td></tr>\
         <tr><th>Tree</th><td><a href=\"{tree}\">browse</a></td></tr>\
         <tr><th>Patch</th><td><a href=\"{patch}\">download (mbox)</a></td></tr>\
         </tbody></table>\
         <p class=\"muted\">{nfiles} file(s) changed, \
         <span class=\"stat-add\">+{total_add}</span> \
         <span class=\"stat-del\">-{total_del}</span></p></div></div>",
        sha = esc(&commit.sha),
        an = esc(&commit.author_name),
        ae = esc(&commit.author_email),
        ad = esc(&commit.author_date),
        cn = esc(&commit.committer_name),
        ce = esc(&commit.committer_email),
        cd = esc(&commit.committer_date),
        tree = esc(&ctx.action(&repo.name, "tree", &[("ref", &commit.sha)])),
        patch = esc(&ctx.action(&repo.name, "commit.patch", &[("id", &commit.sha)])),
        nfiles = files.len(),
    ));
    let body = meta + &render_diff(files);
    page(
        ctx,
        &format!("{}: {}", repo.name, commit.short),
        &body,
        Some(&repo.name),
        "log",
        &repo.description,
    )
}

// --------------------------------------------------------------------------- //
// Tree + breadcrumbs
// --------------------------------------------------------------------------- //

fn crumb_bar(
    ctx: &Ctx,
    repo_name: &str,
    reference: &str,
    path: &str,
    leaf_is_blob: bool,
) -> String {
    let mut crumbs = vec![format!(
        "<a href=\"{}\">{}</a>",
        esc(&ctx.action(repo_name, "tree", &[("ref", reference)])),
        esc(repo_name)
    )];
    let parts: Vec<&str> = path.split('/').filter(|p| !p.is_empty()).collect();
    let mut accum = String::new();
    for (idx, part) in parts.iter().enumerate() {
        if accum.is_empty() {
            accum = (*part).to_string();
        } else {
            accum = format!("{accum}/{part}");
        }
        if idx == parts.len() - 1 && leaf_is_blob {
            crumbs.push(esc(part));
        } else {
            let url = ctx.action(repo_name, "tree", &[("ref", reference), ("path", &accum)]);
            crumbs.push(format!("<a href=\"{}\">{}</a>", esc(&url), esc(part)));
        }
    }
    format!(
        "<div class=\"crumbs mono\">{} <span class=\"pill\">{}</span></div>",
        crumbs.join(" <span class=\"muted\">/</span> "),
        esc(reference)
    )
}

/// The branch/tag/permalink choices the ref switcher offers, shared by the tree
/// and blob views.
#[derive(Clone, Copy, Debug, Default)]
pub struct RefChoices<'a> {
    /// Branch names to offer.
    pub branches: &'a [String],
    /// Tag names to offer.
    pub tags: &'a [String],
    /// The resolved commit sha behind the current ref, for the permalink
    /// (empty to omit it).
    pub commit_sha: &'a str,
}

/// A rendered README to append below a listing (`html`), plus the filename to
/// title the box with (`name`, defaulting to `README`).
#[derive(Clone, Copy, Debug, Default)]
pub struct Readme<'a> {
    /// The already-safe rendered HTML, or `None` for no README box at all.
    pub html: Option<&'a str>,
    /// The README's filename.
    pub name: Option<&'a str>,
}

/// A no-JS ref switcher (HTML5 `<details>`) plus a sha-pinned permalink.
///
/// Every entry is a plain link that keeps the current `action`/`path` and only
/// swaps the ref, so switching branches/tags needs neither JavaScript nor a form
/// (our CSP forbids submitting one anywhere but `self`). The permalink pins the
/// current view to the resolved commit sha for a stable, immutable URL.
#[must_use]
pub fn ref_switcher(
    ctx: &Ctx,
    repo_name: &str,
    action: &str,
    reference: &str,
    path: &str,
    choices: &RefChoices<'_>,
) -> String {
    let links = |names: &[String]| -> String {
        if names.is_empty() {
            return "<span class=\"muted\">none</span>".to_string();
        }
        names
            .iter()
            .map(|name| {
                let url = ctx.action(repo_name, action, &[("ref", name), ("path", path)]);
                let marker = if name == reference { " &check;" } else { "" };
                format!("<a href=\"{}\">{}{marker}</a>", esc(&url), esc(name))
            })
            .collect::<Vec<_>>()
            .join(" ")
    };
    let mut out =
        String::from("<details class=\"switch\"><summary>Switch ref &amp; permalink</summary>");
    out.push_str("<div class=\"menu\">");
    out.push_str(&format!(
        "<div><strong>Branches:</strong> {}</div>",
        links(choices.branches)
    ));
    out.push_str(&format!(
        "<div><strong>Tags:</strong> {}</div>",
        links(choices.tags)
    ));
    if !choices.commit_sha.is_empty() {
        let perma = ctx.action(
            repo_name,
            action,
            &[("ref", choices.commit_sha), ("path", path)],
        );
        out.push_str(&format!(
            "<div><strong>Permalink:</strong> <a class=\"mono\" href=\"{}\">{}</a></div>",
            esc(&perma),
            esc(&choices.commit_sha.chars().take(12).collect::<String>())
        ));
    }
    out.push_str("</div></details>");
    out
}

fn tree_pager(
    ctx: &Ctx,
    repo_name: &str,
    reference: &str,
    path: &str,
    page_num: usize,
    total_pages: usize,
) -> String {
    if total_pages <= 1 {
        return String::new();
    }
    let mut out = String::from("<div class=\"pager\">");
    if page_num > 1 {
        let prev = ctx.action(
            repo_name,
            "tree",
            &[
                ("ref", reference),
                ("path", path),
                ("page", &(page_num - 1).to_string()),
            ],
        );
        out.push_str(&format!("<a href=\"{}\">&larr; Prev</a>", esc(&prev)));
    } else {
        out.push_str("<span class=\"disabled\">&larr; Prev</span>");
    }
    out.push_str(&format!(
        "<span class=\"disabled\">page {page_num} of {total_pages}</span>"
    ));
    if page_num < total_pages {
        let next = ctx.action(
            repo_name,
            "tree",
            &[
                ("ref", reference),
                ("path", path),
                ("page", &(page_num + 1).to_string()),
            ],
        );
        out.push_str(&format!("<a href=\"{}\">Next &rarr;</a>", esc(&next)));
    } else {
        out.push_str("<span class=\"disabled\">Next &rarr;</span>");
    }
    out.push_str("</div>");
    out
}

/// Everything the tree view needs beyond the repo/ref/path triple.
#[derive(Clone, Copy, Debug, Default)]
pub struct TreeView<'a> {
    /// 1-based page of the (paginated) directory listing.
    pub page_num: usize,
    /// Total number of pages.
    pub total_pages: usize,
    /// Total entries in the directory, when pagination is in play.
    pub total_entries: Option<usize>,
    /// What the ref switcher offers.
    pub refs: RefChoices<'a>,
    /// `.gitmodules` `path` → `url`, for gitlink entries.
    pub submodules: &'a [(String, String)],
}

/// A directory listing, with breadcrumbs, ref switcher, pager and README.
#[must_use]
pub fn tree_page(
    ctx: &Ctx,
    repo: &Repo,
    reference: &str,
    path: &str,
    entries: &[TreeEntry],
    readme: &Readme<'_>,
    view: &TreeView<'_>,
) -> String {
    let bar = crumb_bar(ctx, &repo.name, reference, path, false);
    let switcher = ref_switcher(ctx, &repo.name, "tree", reference, path, &view.refs);
    let mut rows = String::new();
    if !path.is_empty() && view.page_num == 1 {
        let mut segs: Vec<&str> = path.split('/').collect();
        segs.pop();
        let parent = segs.join("/");
        let up = ctx.action(&repo.name, "tree", &[("ref", reference), ("path", &parent)]);
        rows.push_str(&format!(
            "<tr><td colspan=\"3\"><a href=\"{}\">..</a></td></tr>",
            esc(&up)
        ));
    }
    for e in entries {
        let mut submodule_extra = String::new();
        let (url, icon) = if e.otype == "tree" {
            (
                ctx.action(&repo.name, "tree", &[("ref", reference), ("path", &e.path)]),
                "dir",
            )
        } else if e.otype == "commit" {
            // A gitlink: show the pinned sha and, when known, the upstream URL.
            let pin = format!(
                "<span class=\"mono muted\"> @ {}</span>",
                esc(&e.sha.chars().take(12).collect::<String>())
            );
            let sub_url = view
                .submodules
                .iter()
                .find(|(p, _)| *p == e.path)
                .map(|(_, u)| u.as_str());
            let link = match sub_url {
                Some(u) => match safe_external(u) {
                    Some(safe) => format!(
                        " <a href=\"{safe}\" rel=\"nofollow noopener\">{}</a>",
                        esc(u)
                    ),
                    None => format!(" <span class=\"muted\">{}</span>", esc(u)),
                },
                None => String::new(),
            };
            submodule_extra = pin + &link;
            (String::new(), "submodule")
        } else {
            (
                ctx.action(&repo.name, "blob", &[("ref", reference), ("path", &e.path)]),
                "file",
            )
        };
        let name_cell = if url.is_empty() {
            esc(&e.name)
        } else {
            format!("<a href=\"{}\">{}</a>", esc(&url), esc(&e.name))
        };
        let size = e.size.map_or_else(String::new, |s| s.to_string());
        rows.push_str(&format!(
            "<tr><td class=\"mono muted\">{}</td>\
             <td>{name_cell} <span class=\"pill\">{icon}</span>{submodule_extra}</td>\
             <td class=\"muted\" style=\"text-align:right\">{}</td></tr>",
            esc(&e.mode),
            esc(&size),
        ));
    }
    let count_note = match view.total_entries {
        Some(total) if view.total_pages > 1 => {
            format!("<div class=\"box-head muted\">{total} entries</div>")
        }
        _ => String::new(),
    };
    let table = format!(
        "<div class=\"box\">{count_note}<table class=\"list\"><thead><tr><th>Mode</th>\
         <th>Name</th><th>Size</th></tr></thead><tbody>{rows}</tbody></table></div>"
    );
    let pager = tree_pager(
        ctx,
        &repo.name,
        reference,
        path,
        view.page_num,
        view.total_pages,
    );
    let readme_box = match readme.html {
        Some(html) => format!(
            "<div class=\"box\"><div class=\"box-head\">{}</div>\
             <div class=\"box-body readme\">{html}</div></div>",
            esc(readme.name.unwrap_or("README"))
        ),
        None => String::new(),
    };
    let title = format!(
        "{}: {}",
        repo.name,
        if path.is_empty() { "/" } else { path }
    );
    page(
        ctx,
        &title,
        &(bar + &switcher + &table + &pager + &readme_box),
        Some(&repo.name),
        "tree",
        &repo.description,
    )
}

// --------------------------------------------------------------------------- //
// Blob
// --------------------------------------------------------------------------- //

/// Render `text` as a line-numbered, anchored table of escaped source lines.
///
/// `hl` holds the 1-based line numbers to highlight (the `?highlight=` range).
#[must_use]
pub fn numbered_lines(text: &str, hl: &[usize]) -> String {
    let mut lines: Vec<&str> = text.split('\n').collect();
    // Drop the trailing empty element produced by a final newline.
    if lines.last() == Some(&"") {
        lines.pop();
    }
    let mut rows = String::new();
    for (i, line) in lines.iter().enumerate() {
        let n = i + 1;
        let cls = if hl.contains(&n) { " class=\"hl\"" } else { "" };
        rows.push_str(&format!(
            "<tr id=\"L{n}\"{cls}><td class=\"lineno\"><a href=\"#L{n}\">{n}</a></td>\
             <td class=\"line\">{}</td></tr>",
            esc(line)
        ));
    }
    format!("<table class=\"code\"><tbody>{rows}</tbody></table>")
}

/// Everything the blob view needs beyond the repo/ref/path triple.
#[derive(Clone, Copy, Debug, Default)]
pub struct BlobView<'a> {
    /// The blob's size in bytes (the LFS object's size when one is served).
    pub size: u64,
    /// The decoded text, when it is being rendered inline.
    pub text: Option<&'a str>,
    /// git considers the content binary.
    pub binary: bool,
    /// The blob is over the inline-display cap.
    pub too_large: bool,
    /// Render inline as an `<img>` pointing at `/raw`.
    pub is_image: bool,
    /// 1-based line numbers to highlight.
    pub highlight: &'a [usize],
    /// What the ref switcher offers.
    pub refs: RefChoices<'a>,
    /// An LFS pointer whose object is **not** in local storage (show the pointer).
    pub lfs: Option<&'a LfsPointer>,
    /// An LFS pointer whose object **is** in local storage (real content shown).
    pub lfs_served: Option<&'a LfsPointer>,
    /// Rendered Markdown, when the blob is a Markdown document.
    pub rendered_md: Option<&'a str>,
    /// `?display=source`: show the numbered source instead of the rendering.
    pub show_source: bool,
}

/// One file: raw/blame/history actions plus the content (source, image, LFS
/// pointer, rendered Markdown, or a "too large"/"binary" notice).
#[must_use]
pub fn blob_page(
    ctx: &Ctx,
    repo: &Repo,
    reference: &str,
    path: &str,
    view: &BlobView<'_>,
) -> String {
    let bar = crumb_bar(ctx, &repo.name, reference, path, true);
    let switcher = ref_switcher(ctx, &repo.name, "blob", reference, path, &view.refs);
    let raw_url = ctx.action(&repo.name, "raw", &[("ref", reference), ("path", path)]);
    let blame_url = ctx.action(&repo.name, "blame", &[("ref", reference), ("path", path)]);
    let history_url = ctx.action(&repo.name, "history", &[("ref", reference), ("path", path)]);
    let mut actions = format!(
        "<div class=\"pager\"><a href=\"{}\">Raw</a><a href=\"{}\">Blame</a>\
         <a href=\"{}\">History</a><span class=\"disabled\">{} bytes</span></div>",
        esc(&raw_url),
        esc(&blame_url),
        esc(&history_url),
        view.size,
    );
    // When the real content of an LFS-tracked file is being served from local
    // storage, surface a small note (the oid the bytes came from).
    if let Some(served) = view.lfs_served {
        actions.push_str(&format!(
            "<p class=\"muted\">Stored with Git LFS &mdash; served from local \
             storage (oid sha256:{}&hellip;).</p>",
            esc(&served.oid.chars().take(16).collect::<String>())
        ));
    }

    let body = if let Some(lfs) = view.lfs {
        format!(
            "<div class=\"box\"><div class=\"box-head\">Git LFS pointer</div>\
             <div class=\"box-body\">\
             <p>This file is stored with Git LFS and its object is not in this \
             server's local LFS storage, so only the pointer is shown.</p>\
             <table class=\"list\"><tbody>\
             <tr><th>oid</th><td class=\"mono\">sha256:{}</td></tr>\
             <tr><th>size</th><td>{} bytes</td></tr></tbody></table>\
             <p><a href=\"{}\">Download pointer (raw)</a></p></div></div>",
            esc(&lfs.oid),
            lfs.size,
            esc(&raw_url)
        )
    } else if view.is_image {
        // CSP img-src 'self' permits this; /raw serves the correct image type.
        format!(
            "<div class=\"box\"><div class=\"box-body\" style=\"text-align:center\">\
             <img class=\"blob-img\" src=\"{}\" alt=\"{}\"></div></div>",
            esc(&raw_url),
            esc(path)
        )
    } else if view.binary {
        format!(
            "<div class=\"warn\">Binary file &mdash; {} bytes. \
             <a href=\"{}\">Download raw</a>.</div>",
            view.size,
            esc(&raw_url)
        )
    } else if view.too_large {
        format!(
            "<div class=\"warn\">File is {} bytes, larger than the inline display limit. \
             <a href=\"{}\">View raw</a>.</div>",
            view.size,
            esc(&raw_url)
        )
    } else if view.rendered_md.is_some() && !view.show_source {
        // A Markdown blob rendered, with a toggle to the raw numbered source.
        let src_url = ctx.action(
            &repo.name,
            "blob",
            &[("ref", reference), ("path", path), ("display", "source")],
        );
        format!(
            "<div class=\"pager\"><a href=\"{}\">View source</a></div>\
             <div class=\"box\"><div class=\"box-body readme\">{}</div></div>",
            esc(&src_url),
            view.rendered_md.unwrap_or("")
        )
    } else {
        let toggle = match view.rendered_md {
            Some(_) => {
                let rendered_url =
                    ctx.action(&repo.name, "blob", &[("ref", reference), ("path", path)]);
                format!(
                    "<div class=\"pager\"><a href=\"{}\">View rendered</a></div>",
                    esc(&rendered_url)
                )
            }
            None => String::new(),
        };
        toggle + &numbered_lines(view.text.unwrap_or(""), view.highlight)
    };
    page(
        ctx,
        &format!("{}: {path}", repo.name),
        &(bar + &switcher + &actions + &body),
        Some(&repo.name),
        "tree",
        &repo.description,
    )
}

// --------------------------------------------------------------------------- //
// Blame
// --------------------------------------------------------------------------- //

/// Per-line authorship for one file.
#[must_use]
pub fn blame_page(
    ctx: &Ctx,
    repo: &Repo,
    reference: &str,
    path: &str,
    lines: &[BlameLine],
) -> String {
    let bar = crumb_bar(ctx, &repo.name, reference, path, true);
    let blob_url = ctx.action(&repo.name, "blob", &[("ref", reference), ("path", path)]);
    let actions = format!(
        "<div class=\"pager\"><a href=\"{}\">Normal view</a></div>",
        esc(&blob_url)
    );
    let mut rows = String::new();
    for bl in lines {
        let commit_url = ctx.action(&repo.name, "commit", &[("id", &bl.short)]);
        rows.push_str(&format!(
            "<tr id=\"L{n}\"><td class=\"b-sha mono\"><a href=\"{}\">{}</a></td>\
             <td class=\"b-auth\">{}</td>\
             <td class=\"lineno\"><a href=\"#L{n}\">{n}</a></td>\
             <td class=\"line\">{}</td></tr>",
            esc(&commit_url),
            esc(&bl.short),
            esc(&bl.author),
            esc(&bl.content),
            n = bl.lineno,
        ));
    }
    let table = format!("<table class=\"code\"><tbody>{rows}</tbody></table>");
    page(
        ctx,
        &format!("{}: blame {path}", repo.name),
        &(bar + &actions + &table),
        Some(&repo.name),
        "tree",
        &repo.description,
    )
}

// --------------------------------------------------------------------------- //
// History (per-file log)
// --------------------------------------------------------------------------- //

/// How the per-file history is paginated, and whether renames are followed.
#[derive(Clone, Copy, Debug, Default)]
pub struct HistoryView {
    /// 1-based page number.
    pub page_num: usize,
    /// Total pages.
    pub total_pages: usize,
    /// `--follow` (rename tracking) is on.
    pub follow: bool,
}

/// The commits touching one path, optionally following renames.
#[must_use]
pub fn history_page(
    ctx: &Ctx,
    repo: &Repo,
    reference: &str,
    path: &str,
    rows: &[CommitRow],
    view: &HistoryView,
) -> String {
    let HistoryView {
        page_num,
        total_pages,
        follow,
    } = *view;
    let bar = crumb_bar(ctx, &repo.name, reference, path, true);
    let blob_url = ctx.action(&repo.name, "blob", &[("ref", reference), ("path", path)]);
    let (toggle, toggle_label) = if follow {
        (
            ctx.action(&repo.name, "history", &[("ref", reference), ("path", path)]),
            "Disable follow",
        )
    } else {
        (
            ctx.action(
                &repo.name,
                "history",
                &[("ref", reference), ("path", path), ("follow", "1")],
            ),
            "Follow renames",
        )
    };
    let actions = format!(
        "<div class=\"pager\"><a href=\"{}\">View file</a><a href=\"{}\">{}</a></div>",
        esc(&blob_url),
        esc(&toggle),
        esc(toggle_label)
    );
    let header = format!(
        "<p class=\"muted\">History of <span class=\"mono\">{}</span> on \
         <span class=\"pill\">{}</span>{} &mdash; page {page_num} of {}</p>",
        esc(path),
        esc(reference),
        if follow {
            " <span class=\"pill\">follow</span>"
        } else {
            ""
        },
        total_pages.max(1),
    );
    let table = if rows.is_empty() {
        "<p class=\"muted\">No history for this path.</p>".to_string()
    } else {
        format!(
            "<table class=\"list\"><thead><tr><th>Commit</th><th>Subject</th>\
             <th>Author</th><th>When</th></tr></thead><tbody>{}</tbody></table>",
            commit_rows(ctx, &repo.name, rows)
        )
    };
    let follow_param = if follow { "1" } else { "" };
    let mut pager = String::from("<div class=\"pager\">");
    if page_num > 1 {
        let prev = ctx.action(
            &repo.name,
            "history",
            &[
                ("ref", reference),
                ("path", path),
                ("page", &(page_num - 1).to_string()),
                ("follow", follow_param),
            ],
        );
        pager.push_str(&format!("<a href=\"{}\">&larr; Newer</a>", esc(&prev)));
    } else {
        pager.push_str("<span class=\"disabled\">&larr; Newer</span>");
    }
    if page_num < total_pages {
        let next = ctx.action(
            &repo.name,
            "history",
            &[
                ("ref", reference),
                ("path", path),
                ("page", &(page_num + 1).to_string()),
                ("follow", follow_param),
            ],
        );
        pager.push_str(&format!("<a href=\"{}\">Older &rarr;</a>", esc(&next)));
    } else {
        pager.push_str("<span class=\"disabled\">Older &rarr;</span>");
    }
    pager.push_str("</div>");
    page(
        ctx,
        &format!("{}: history {path}", repo.name),
        &(bar + &actions + &header + &table + &pager),
        Some(&repo.name),
        "tree",
        &repo.description,
    )
}

// --------------------------------------------------------------------------- //
// Compare (diff between two refs)
// --------------------------------------------------------------------------- //

/// The diff between two refs.
#[must_use]
pub fn compare_page(ctx: &Ctx, repo: &Repo, base: &str, other: &str, files: &[DiffFile]) -> String {
    let total_add: usize = files.iter().map(|f| f.additions).sum();
    let total_del: usize = files.iter().map(|f| f.deletions).sum();
    let header = format!(
        "<div class=\"box\"><div class=\"box-head\">Compare</div><div class=\"box-body\">\
         <p><span class=\"pill\">{}</span> &rarr; <span class=\"pill\">{}</span></p>\
         <p class=\"muted\">{} file(s) changed, \
         <span class=\"stat-add\">+{total_add}</span> \
         <span class=\"stat-del\">-{total_del}</span></p></div></div>",
        esc(base),
        esc(other),
        files.len(),
    );
    page(
        ctx,
        &format!("{}: compare {base}..{other}", repo.name),
        &(header + &render_diff(files)),
        Some(&repo.name),
        "refs",
        &repo.description,
    )
}

// --------------------------------------------------------------------------- //
// Atom feed
// --------------------------------------------------------------------------- //

/// An Atom 1.0 feed of recent commits on `reference`.
///
/// All dynamic text goes through [`xml_escape`], which additionally drops the C0
/// control characters XML 1.0 forbids — a single such byte in a repo-derived
/// field (commit subject/author/email, or the repo description) would otherwise
/// make the whole feed non-well-formed for every reader. Links are absolute when
/// a `base_url` (`scheme://host`) is known, otherwise relative.
#[must_use]
pub fn atom_feed(
    ctx: &Ctx,
    repo: &Repo,
    reference: &str,
    rows: &[CommitRow],
    base_url: &str,
) -> String {
    let abs = |rel: &str| -> String {
        if base_url.is_empty() {
            rel.to_string()
        } else {
            format!("{base_url}{rel}")
        }
    };
    let self_link = abs(&ctx.action(&repo.name, "atom", &[("ref", reference)]));
    let repo_link = abs(&ctx.repo(&repo.name));
    let updated = atom_date(rows.first().map(|c| c.ts));
    let feed_id = if self_link.is_empty() {
        format!("urn:gitweb:{}:{reference}", repo.name)
    } else {
        self_link.clone()
    };
    let mut out = String::new();
    out.push_str("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
    out.push_str("<feed xmlns=\"http://www.w3.org/2005/Atom\">");
    out.push_str(&format!(
        "<title>{}: {}</title>",
        xml_escape(&repo.name),
        xml_escape(reference)
    ));
    out.push_str(&format!("<id>{}</id>", xml_escape(&feed_id)));
    out.push_str(&format!("<updated>{}</updated>", xml_escape(&updated)));
    out.push_str(&format!(
        "<link rel=\"self\" href=\"{}\"/>",
        xml_escape(&self_link)
    ));
    out.push_str(&format!(
        "<link rel=\"alternate\" href=\"{}\"/>",
        xml_escape(&repo_link)
    ));
    out.push_str("<generator>gitweb</generator>");
    if !repo.description.is_empty() {
        out.push_str(&format!(
            "<subtitle>{}</subtitle>",
            xml_escape(&repo.description)
        ));
    }
    for c in rows {
        let entry_link = abs(&ctx.action(&repo.name, "commit", &[("id", &c.sha)]));
        out.push_str("<entry>");
        out.push_str(&format!("<title>{}</title>", xml_escape(&c.subject)));
        out.push_str(&format!(
            "<id>urn:gitweb:commit:{}</id>",
            xml_escape(&c.sha)
        ));
        out.push_str(&format!(
            "<updated>{}</updated>",
            xml_escape(&atom_date(Some(c.ts)))
        ));
        out.push_str(&format!(
            "<link rel=\"alternate\" href=\"{}\"/>",
            xml_escape(&entry_link)
        ));
        out.push_str(&format!(
            "<author><name>{}</name><email>{}</email></author>",
            xml_escape(&c.author),
            xml_escape(&c.email)
        ));
        out.push_str(&format!(
            "<summary type=\"text\">{}</summary>",
            xml_escape(&c.subject)
        ));
        out.push_str("</entry>");
    }
    out.push_str("</feed>");
    out
}

// --------------------------------------------------------------------------- //
// Search (code + commit message)
// --------------------------------------------------------------------------- //

/// A no-JS search box (a GET form; needs CSP `form-action 'self'`).
fn search_form(ctx: &Ctx, repo_name: &str, q: &str, typ: &str, reference: &str) -> String {
    let action = ctx.action(repo_name, "search", &[]);
    let mut options = String::new();
    for (value, label) in [("code", "Code"), ("log", "Commit messages")] {
        let sel = if value == typ { " selected" } else { "" };
        options.push_str(&format!(
            "<option value=\"{}\"{sel}>{}</option>",
            esc(value),
            esc(label)
        ));
    }
    let ref_hidden = if reference.is_empty() {
        String::new()
    } else {
        format!(
            "<input type=\"hidden\" name=\"ref\" value=\"{}\">",
            esc(reference)
        )
    };
    format!(
        "<form class=\"search\" method=\"get\" action=\"{}\" role=\"search\">\
         <input type=\"search\" name=\"q\" value=\"{}\" \
         placeholder=\"Search…\" aria-label=\"Search query\">\
         <select name=\"type\" aria-label=\"Search type\">{options}</select>\
         {ref_hidden}<button type=\"submit\">Search</button></form>",
        esc(&action),
        esc(q)
    )
}

fn search_code_results(
    ctx: &Ctx,
    repo_name: &str,
    reference: &str,
    matches: &[GrepMatch],
    truncated: bool,
) -> String {
    if matches.is_empty() {
        return "<p class=\"muted\">No code matches.</p>".to_string();
    }
    let mut out = String::new();
    if truncated {
        out.push_str(
            "<div class=\"warn\">Results were truncated (too many matches); \
             refine the query.</div>",
        );
    }
    out.push_str(&format!(
        "<p class=\"muted\">{} match(es).</p>",
        matches.len()
    ));
    // git grep emits all hits for a file consecutively; group preserving order.
    let mut groups: Vec<(&str, Vec<&GrepMatch>)> = Vec::new();
    for m in matches {
        match groups.last_mut() {
            Some((path, hits)) if *path == m.path => hits.push(m),
            _ => groups.push((&m.path, vec![m])),
        }
    }
    for (path, hits) in groups {
        let blob_base = ctx.action(repo_name, "blob", &[("ref", reference), ("path", path)]);
        out.push_str(&format!(
            "<div class=\"box search-file\"><div class=\"box-head\">\
             <a href=\"{}\">{}</a></div>",
            esc(&blob_base),
            esc(path)
        ));
        out.push_str("<table class=\"code grep\"><tbody>");
        for m in hits {
            // `#L<n>` is a fragment appended after the (encoded) query string.
            let line_url = format!("{blob_base}#L{}", m.lineno);
            out.push_str(&format!(
                "<tr><td class=\"lineno\"><a href=\"{}\">{}</a></td>\
                 <td class=\"line\">{}</td></tr>",
                esc(&line_url),
                m.lineno,
                esc(&m.text)
            ));
        }
        out.push_str("</tbody></table></div>");
    }
    out
}

fn search_pager(
    ctx: &Ctx,
    repo_name: &str,
    q: &str,
    reference: &str,
    page_num: usize,
    total_pages: usize,
) -> String {
    if total_pages <= 1 {
        return String::new();
    }
    let link = |page: usize| -> String {
        ctx.action(
            repo_name,
            "search",
            &[
                ("q", q),
                ("type", "log"),
                ("ref", reference),
                ("page", &page.to_string()),
            ],
        )
    };
    let mut out = String::from("<div class=\"pager\">");
    if page_num > 1 {
        out.push_str(&format!(
            "<a href=\"{}\">&larr; Newer</a>",
            esc(&link(page_num - 1))
        ));
    } else {
        out.push_str("<span class=\"disabled\">&larr; Newer</span>");
    }
    out.push_str(&format!(
        "<span class=\"disabled\">page {page_num} of {total_pages}</span>"
    ));
    if page_num < total_pages {
        out.push_str(&format!(
            "<a href=\"{}\">Older &rarr;</a>",
            esc(&link(page_num + 1))
        ));
    } else {
        out.push_str("<span class=\"disabled\">Older &rarr;</span>");
    }
    out.push_str("</div>");
    out
}

/// Everything the search view needs beyond the query/type/ref triple.
#[derive(Clone, Copy, Debug, Default)]
pub struct SearchView<'a> {
    /// `git grep` hits, when the code vertical ran.
    pub code_matches: Option<&'a [GrepMatch]>,
    /// The grep result was clipped by one of the caps.
    pub code_truncated: bool,
    /// Commit rows, when the message vertical ran.
    pub log_rows: Option<&'a [CommitRow]>,
    /// 1-based page of the message-search results.
    pub page_num: usize,
    /// Total pages of message-search results.
    pub total_pages: usize,
    /// The query was empty, too long, or contained an invalid character.
    pub invalid: bool,
}

/// The search page: the form plus either code hits or matching commit messages.
#[must_use]
pub fn search_page(
    ctx: &Ctx,
    repo: &Repo,
    q: &str,
    typ: &str,
    reference: &str,
    view: &SearchView<'_>,
) -> String {
    let mut parts = format!(
        "<p class=\"muted\">Searching <span class=\"pill\">{}</span> \
         &mdash; literal (fixed-string) matching.</p>",
        esc(reference)
    );
    parts.push_str(&search_form(ctx, &repo.name, q, typ, reference));
    if view.invalid {
        parts.push_str(
            "<div class=\"warn\">Query is empty, too long, or contains an \
             invalid character.</div>",
        );
    } else if q.is_empty() {
        parts.push_str(
            "<p class=\"muted\">Enter a term. <strong>Code</strong> searches file \
             contents at this ref; <strong>Commit messages</strong> searches log \
             messages.</p>",
        );
    } else if typ == "log" {
        let rows = view.log_rows.unwrap_or(&[]);
        if rows.is_empty() {
            parts.push_str("<p class=\"muted\">No commit messages match.</p>");
        } else {
            parts.push_str(&format!(
                "<table class=\"list\"><thead><tr><th>Commit</th><th>Subject</th>\
                 <th>Author</th><th>When</th></tr></thead><tbody>{}</tbody></table>",
                commit_rows(ctx, &repo.name, rows)
            ));
            parts.push_str(&search_pager(
                ctx,
                &repo.name,
                q,
                reference,
                view.page_num,
                view.total_pages,
            ));
        }
    } else {
        parts.push_str(&search_code_results(
            ctx,
            &repo.name,
            reference,
            view.code_matches.unwrap_or(&[]),
            view.code_truncated,
        ));
    }
    page(
        ctx,
        &format!("{}: search", repo.name),
        &parts,
        Some(&repo.name),
        "search",
        &repo.description,
    )
}

// --------------------------------------------------------------------------- //
// Commit graph (inline SVG, no JavaScript)
// --------------------------------------------------------------------------- //

/// px per commit row (matches the `.graph-row` height).
const G_ROW_H: i64 = 24;
/// px per lane column.
const G_COL_W: i64 = 16;
/// Commit node radius.
const G_RADIUS: i64 = 4;
/// Horizontal padding inside the SVG.
const G_PAD: i64 = 8;
/// A small fixed palette cycled by lane column (presentation attributes only —
/// no inline `<style>`, no scripting; every value here is a constant).
const G_COLORS: [&str; 8] = [
    "#0969da", "#1a7f37", "#8250df", "#bf3989", "#bc4c00", "#0550ae", "#116329", "#a40e26",
];

/// One commit's position in the lane graph, as [`assign_lanes`] computes it.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LaneNode {
    /// Row index (0 = newest commit on the page).
    pub row: usize,
    /// Lane (column) the commit's node sits in.
    pub col: usize,
    /// The commit sha.
    pub sha: String,
    /// `(parent sha, the lane that parent was assigned)`.
    pub parents: Vec<(String, usize)>,
}

/// Assign each commit a lane (column) and record its parents' lanes.
///
/// A classic column model: `lanes` holds, per column, the sha the column is
/// currently waiting to emit (or `None` when free). Each commit takes the column
/// already waiting for it (or a fresh one); its first parent inherits that column
/// and any extra parents open new columns. Pure and bounded by the page size, so
/// it is cheap and unit-testable.
///
/// Returns `(nodes, max_cols)`.
#[must_use]
pub fn assign_lanes(rows: &[GraphCommit]) -> (Vec<LaneNode>, usize) {
    let mut lanes: Vec<Option<String>> = Vec::new();
    let mut nodes: Vec<LaneNode> = Vec::new();
    let mut max_cols = 1usize;

    for (i, c) in rows.iter().enumerate() {
        let mut my_col = lanes
            .iter()
            .position(|s| s.as_deref() == Some(c.sha.as_str()));
        if my_col.is_none() {
            my_col = Some(match lanes.iter().position(Option::is_none) {
                Some(j) => j,
                None => {
                    lanes.push(None);
                    lanes.len() - 1
                }
            });
        }
        let my_col = my_col.unwrap_or(0);
        // Converging merges: free any *other* lane also waiting for this commit.
        for (j, s) in lanes.iter_mut().enumerate() {
            if j != my_col && s.as_deref() == Some(c.sha.as_str()) {
                *s = None;
            }
        }
        let mut parent_cols: Vec<(String, usize)> = Vec::new();
        if let Some(first) = c.parents.first() {
            lanes[my_col] = Some(first.clone());
            parent_cols.push((first.clone(), my_col));
            for p in &c.parents[1..] {
                let col = match lanes.iter().position(|s| s.as_deref() == Some(p.as_str())) {
                    Some(col) => col,
                    None => {
                        let col = match lanes.iter().position(Option::is_none) {
                            Some(j) => j,
                            None => {
                                lanes.push(None);
                                lanes.len() - 1
                            }
                        };
                        lanes[col] = Some(p.clone());
                        col
                    }
                };
                parent_cols.push((p.clone(), col));
            }
        } else {
            lanes[my_col] = None; // root: the lane ends here
        }
        nodes.push(LaneNode {
            row: i,
            col: my_col,
            sha: c.sha.clone(),
            parents: parent_cols,
        });
        // `lanes.len()` here is the highest column index+1 currently allocated
        // (columns can be sparse), i.e. the width this row needs.
        max_cols = max_cols.max(lanes.len());
        while lanes.last().is_some_and(Option::is_none) {
            lanes.pop();
        }
    }
    (nodes, max_cols)
}

/// Render the lane graph as inline SVG beside a column of commit rows.
///
/// Geometry is built only from integers and the fixed colour palette, so no
/// repository-derived text ever reaches an SVG attribute; the commit metadata
/// (escaped) lives in the adjacent HTML rows, which share the row height so the
/// nodes line up.
fn render_graph_svg(
    ctx: &Ctx,
    repo_name: &str,
    nodes: &[LaneNode],
    rows: &[GraphCommit],
    max_cols: usize,
) -> String {
    let n = rows.len() as i64;
    let height = n * G_ROW_H;
    let width = G_PAD * 2 + (max_cols.max(1) as i64) * G_COL_W;
    let find_node = |sha: &str| nodes.iter().find(|nd| nd.sha == sha);
    let cx = |col: usize| -> i64 { G_PAD + (col as i64) * G_COL_W + G_COL_W / 2 };
    let cy = |row: usize| -> i64 { (row as i64) * G_ROW_H + G_ROW_H / 2 };

    let mut edges = String::new();
    let mut dots = String::new();
    for nd in nodes {
        let (x0, y0) = (cx(nd.col), cy(nd.row));
        for (psha, assigned_col) in &nd.parents {
            let parent = find_node(psha);
            // Parent off this page: draw a stub to the bottom; otherwise connect
            // to where the parent node actually renders.
            let (xp, yp) = match parent {
                Some(p) => (cx(p.col), cy(p.row)),
                None => (cx(*assigned_col), height),
            };
            let color_col = parent.map_or(*assigned_col, |p| p.col);
            let color = G_COLORS[color_col % G_COLORS.len()];
            let d = if xp == x0 {
                format!("M{x0} {y0} L{xp} {yp}")
            } else {
                // Kink one row below the child, then run straight down the lane.
                let ykink = match parent {
                    Some(_) => (y0 + G_ROW_H).min(yp),
                    None => y0 + G_ROW_H,
                };
                format!("M{x0} {y0} L{xp} {ykink} L{xp} {yp}")
            };
            edges.push_str(&format!(
                "<path d=\"{d}\" fill=\"none\" stroke=\"{color}\" stroke-width=\"1.5\"/>"
            ));
        }
        let dot_color = G_COLORS[nd.col % G_COLORS.len()];
        dots.push_str(&format!(
            "<circle cx=\"{x0}\" cy=\"{y0}\" r=\"{G_RADIUS}\" \
             fill=\"{dot_color}\" stroke=\"#ffffff\" stroke-width=\"1\"/>"
        ));
    }
    let svg = format!(
        "<svg class=\"graph-svg\" width=\"{width}\" height=\"{height}\" \
         viewBox=\"0 0 {width} {height}\" xmlns=\"http://www.w3.org/2000/svg\" \
         role=\"img\" aria-label=\"commit graph\">{edges}{dots}</svg>"
    );
    let mut row_html = String::new();
    for nd in nodes {
        let Some(c) = rows.get(nd.row) else { continue };
        let url = ctx.action(repo_name, "commit", &[("id", &c.sha)]);
        row_html.push_str(&format!(
            "<div class=\"graph-row\"><a class=\"mono\" href=\"{}\">{}</a> {} \
             <span class=\"muted\">&middot; {}, {}</span></div>",
            esc(&url),
            esc(&c.short),
            esc(&c.subject),
            esc(&c.author),
            esc(&ctx.rel(Some(c.ts))),
        ));
    }
    format!("<div class=\"graph-wrap\">{svg}<div class=\"graph-rows\">{row_html}</div></div>")
}

fn graph_pager(
    ctx: &Ctx,
    repo_name: &str,
    reference: &str,
    page_num: usize,
    total_pages: usize,
) -> String {
    let mut out = String::from("<div class=\"pager\">");
    if page_num > 1 {
        let prev = ctx.action(
            repo_name,
            "graph",
            &[("ref", reference), ("page", &(page_num - 1).to_string())],
        );
        out.push_str(&format!("<a href=\"{}\">&larr; Newer</a>", esc(&prev)));
    } else {
        out.push_str("<span class=\"disabled\">&larr; Newer</span>");
    }
    if page_num < total_pages {
        let next = ctx.action(
            repo_name,
            "graph",
            &[("ref", reference), ("page", &(page_num + 1).to_string())],
        );
        out.push_str(&format!("<a href=\"{}\">Older &rarr;</a>", esc(&next)));
    } else {
        out.push_str("<span class=\"disabled\">Older &rarr;</span>");
    }
    out.push_str("</div>");
    out
}

/// The commit graph: an inline SVG lane diagram beside the commit rows.
#[must_use]
pub fn graph_page(
    ctx: &Ctx,
    repo: &Repo,
    reference: &str,
    rows: &[GraphCommit],
    page_num: usize,
    total_pages: usize,
) -> String {
    let header = format!(
        "<p class=\"muted\">Commit graph for <span class=\"pill\">{}</span> \
         &mdash; page {page_num} of {}</p>",
        esc(reference),
        total_pages.max(1)
    );
    let body = if rows.is_empty() {
        header + "<p class=\"muted\">No commits.</p>"
    } else {
        let (nodes, max_cols) = assign_lanes(rows);
        header
            + &render_graph_svg(ctx, &repo.name, &nodes, rows, max_cols)
            + &graph_pager(ctx, &repo.name, reference, page_num, total_pages)
    };
    page(
        ctx,
        &format!("{}: graph", repo.name),
        &body,
        Some(&repo.name),
        "graph",
        &repo.description,
    )
}

// --------------------------------------------------------------------------- //
// OpenSearch descriptors
// --------------------------------------------------------------------------- //
//
// `{searchTerms}` is the OpenSearch template token the browser substitutes; it
// must survive verbatim into the `template` attribute. The URL is built from
// already-safe pieces (a server-derived base, the url-prefix, a URL-quoted repo
// name) and then run through `xml_escape`, which turns the single `&` between
// query parameters into `&amp;` (required in an XML attribute) while leaving the
// `{…}` token untouched.

/// The OpenSearch template token a browser substitutes.
const SEARCH_TERMS: &str = "{searchTerms}";

/// Per-repo code-search descriptor. `base` is `scheme://host` + the url prefix.
#[must_use]
pub fn opensearch_repo(repo_name: &str, base: &str) -> String {
    let template = format!(
        "{base}/{}/search?q={SEARCH_TERMS}&type=code",
        quote(repo_name, "")
    );
    let short: String = format!("gw:{repo_name}").chars().take(16).collect();
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\
         <OpenSearchDescription xmlns=\"http://a9.com/-/spec/opensearch/1.1/\">\
         <ShortName>{}</ShortName><Description>{}</Description>\
         <InputEncoding>UTF-8</InputEncoding>\
         <Url type=\"text/html\" method=\"get\" template=\"{}\"/>\
         </OpenSearchDescription>",
        xml_escape(&short),
        xml_escape(&format!("Code search in {repo_name}")),
        xml_escape(&template),
    )
}

/// Site-level descriptor: its search targets the repository finder (home).
#[must_use]
pub fn opensearch_site(base: &str) -> String {
    let template = format!("{base}/?q={SEARCH_TERMS}");
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\
         <OpenSearchDescription xmlns=\"http://a9.com/-/spec/opensearch/1.1/\">\
         <ShortName>gitweb</ShortName>\
         <Description>Find a repository on this gitweb</Description>\
         <InputEncoding>UTF-8</InputEncoding>\
         <Url type=\"text/html\" method=\"get\" template=\"{}\"/>\
         </OpenSearchDescription>",
        xml_escape(&template)
    )
}

/// The views that take a whole [`Repo`] cannot be unit-tested here: a
/// `RepoPath` is only mintable by `gitcmd`'s confinement check, by design. Those
/// views are covered — byte-for-byte against the Python reference, over a real
/// fixture repository — in `tests/xcheck_views.rs`.
#[cfg(test)]
mod tests {
    use super::*;

    fn ctx() -> Ctx {
        Ctx::at("", 1_600_000_000.0)
    }

    #[test]
    fn url_builders_match_python() {
        let c = Ctx::new("");
        assert_eq!(c.home(), "/");
        assert_eq!(c.repo("my repo"), "/my%20repo/");
        assert_eq!(c.action("r", "log", &[]), "/r/log");
        assert_eq!(
            c.action("r", "log", &[("ref", "main"), ("page", "")]),
            "/r/log?ref=main"
        );
        assert_eq!(
            c.action("r", "blob", &[("ref", "a/b"), ("path", "x y.txt")]),
            "/r/blob?ref=a%2Fb&path=x+y.txt"
        );
        let p = Ctx::new("/git");
        assert_eq!(p.home(), "/git/");
        assert_eq!(p.repo("r"), "/git/r/");
        assert_eq!(p.action("r", "refs", &[]), "/git/r/refs");
    }

    #[test]
    fn external_submodule_urls_must_be_http() {
        assert_eq!(
            safe_external("https://example.com/x.git"),
            Some("https://example.com/x.git".to_string())
        );
        assert_eq!(safe_external("javascript:alert(1)"), None);
        assert_eq!(safe_external("git@example.com:x.git"), None);
        assert_eq!(safe_external(""), None);
    }

    #[test]
    fn error_page_escapes_and_has_no_script() {
        let html = error_page(&ctx(), 404, "<script>alert(1)</script>");
        assert!(html.starts_with("<!doctype html>"));
        assert!(html.contains("&lt;script&gt;alert(1)&lt;/script&gt;"));
        assert!(!html.contains("<script>"));
        assert!(html.ends_with("</body></html>"));
    }

    #[test]
    fn numbered_lines_escapes_and_anchors() {
        let html = numbered_lines("a = 1 < 2\n<b>\n", &[2]);
        assert!(html.contains("1 &lt; 2"));
        assert!(html.contains("id=\"L1\"><td class=\"lineno\"><a href=\"#L1\">1</a>"));
        assert!(html.contains("id=\"L2\" class=\"hl\""));
        assert!(!html.contains("<b>"));
    }

    #[test]
    fn ref_switcher_marks_the_current_ref() {
        let branches = vec!["main".to_string(), "feature".to_string()];
        let html = ref_switcher(
            &ctx(),
            "r",
            "tree",
            "main",
            "",
            &RefChoices {
                branches: &branches,
                tags: &[],
                commit_sha: "0123456789abcdef",
            },
        );
        assert!(html.contains("main &check;"));
        assert!(html.contains(">feature</a>"));
        assert!(html.contains("Permalink"));
        assert!(html.contains(">0123456789ab</a>"));
        assert!(html.contains("<span class=\"muted\">none</span>")); // no tags
    }

    #[test]
    fn assign_lanes_handles_a_merge() {
        let commit = |sha: &str, parents: &[&str]| GraphCommit {
            sha: sha.to_string(),
            short: sha[..4.min(sha.len())].to_string(),
            parents: parents.iter().map(|p| (*p).to_string()).collect(),
            author: "a".to_string(),
            ts: 0,
            subject: "s".to_string(),
        };
        let rows = vec![
            commit("m", &["a", "b"]),
            commit("a", &["root"]),
            commit("b", &["root"]),
            commit("root", &[]),
        ];
        let (nodes, max_cols) = assign_lanes(&rows);
        assert_eq!(nodes.len(), 4);
        assert_eq!(nodes[0].parents.len(), 2);
        assert_ne!(nodes[0].parents[0].1, nodes[0].parents[1].1);
        assert!(max_cols >= 2);
    }

    #[test]
    fn opensearch_descriptors_keep_the_template_token() {
        let repo = opensearch_repo("my<repo>", "http://h/git");
        assert!(repo.contains("{searchTerms}"));
        assert!(repo.contains("&amp;type=code"));
        assert!(repo.contains("my%3Crepo%3E/search"));
        assert!(!repo.contains("<repo>"));
        let site = opensearch_site("http://h");
        assert!(site.contains("template=\"http://h/?q={searchTerms}\""));
    }

    #[test]
    fn diff_rendering_escapes_every_line() {
        use crate::markup::parse_patch;
        let files = parse_patch(
            "diff --git a/<x>.txt b/<x>.txt\n\
             index 111..222 100644\n\
             --- a/<x>.txt\n\
             +++ b/<x>.txt\n\
             @@ -1 +1 @@\n\
             -<old>\n\
             +<script>alert(1)</script>\n",
        );
        let html = render_diff(&files);
        assert!(html.contains("&lt;script&gt;alert(1)&lt;/script&gt;"));
        assert!(html.contains("class=\"path\">&lt;x&gt;.txt<"));
        assert!(html.contains("class=\"stat-add\">+1<"));
        assert!(html.contains("class=\"diff-del\""));
        assert!(!html.contains("<script>"));
        assert_eq!(
            render_diff(&[]),
            "<p class=\"muted\">No changes (empty or merge commit).</p>"
        );
    }
}
