// Exercises `search` (net) + `build_torrent_file`.
#![cfg(feature = "net")]
//! Cross-check: the serving layer's deterministic helpers are byte-identical to
//! the Python reference (`legacy-python/torrentds/{search,metadata}.py`) —
//! `human_size`, `build_torrent_file` and the **whole rendered search/browse
//! page** (form + filter selects + result rows + pager) — plus a loopback
//! round-trip of the async HTTP server over a live `Store`.
//!
//! The page corpus in `goldens/search.rs` is generated by driving the real
//! Python `render_results`/`render_browse` (see `regen_search_goldens.py`); the
//! inline stylesheet is elided as `<style>@CSS@</style>` and pinned separately as
//! `PY_CSS`, so drift in either the markup or the CSS is a failing test.

include!("goldens/search.rs");

use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpStream;
use torrentds::bencode::{encode, Ben};
use torrentds::metadata::{build_torrent_file, TorrentMeta};
use torrentds::search::{
    human_size, render_browse, render_results, rfc2822, serve_search, torznab_caps, Page,
    SearchServer, UiFilters, PAGE_CSS,
};
use torrentds::store::{Order, SearchResult, Stats, Store};

fn to_hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

#[test]
fn human_size_matches_python() {
    // Goldens from search.human_size(n).
    assert_eq!(human_size(0), "0 B");
    assert_eq!(human_size(512), "512 B");
    assert_eq!(human_size(1024), "1.0 KiB");
    assert_eq!(human_size(1536), "1.5 KiB");
    assert_eq!(human_size(1_073_741_824), "1.0 GiB");
    assert_eq!(human_size(1_400_000_000), "1.3 GiB");
    assert_eq!(human_size(5_497_558_138_880), "5.0 TiB");
}

fn sample_info() -> Vec<u8> {
    let mut m = std::collections::BTreeMap::new();
    m.insert(b"length".to_vec(), Ben::Int(1234));
    m.insert(b"name".to_vec(), Ben::Bytes(b"test.txt".to_vec()));
    m.insert(b"piece length".to_vec(), Ben::Int(16384));
    m.insert(b"pieces".to_vec(), Ben::Bytes(vec![1u8; 20]));
    encode(&Ben::Dict(m))
}

#[test]
fn build_torrent_file_matches_python() {
    let info = sample_info();
    // info spliced verbatim; top-level keys canonical.
    assert_eq!(
        to_hex(&build_torrent_file(&info, None, &[], None)),
        "64343a696e666f64363a6c656e677468693132333465343a6e616d65383a746573742e74787431323a7069656365206c656e67746869313633383465363a70696563657332303a01010101010101010101010101010101010101016565"
    );
    let al = vec!["http://a/x".to_string(), "http://b/y".to_string()];
    assert_eq!(
        to_hex(&build_torrent_file(&info, Some("http://tr/announce"), &al, Some(1_600_000_000))),
        "64383a616e6e6f756e636531383a687474703a2f2f74722f616e6e6f756e636531333a616e6e6f756e63652d6c6973746c6c31303a687474703a2f2f612f78656c31303a687474703a2f2f622f79656531333a6372656174696f6e2064617465693136303030303030303065343a696e666f64363a6c656e677468693132333465343a6e616d65383a746573742e74787431323a7069656365206c656e67746869313633383465363a70696563657332303a01010101010101010101010101010101010101016565"
    );
}

#[test]
fn rfc2822_matches_python_formatdate() {
    assert_eq!(rfc2822(0), "Thu, 01 Jan 1970 00:00:00 GMT");
    assert_eq!(rfc2822(1_600_000_000), "Sun, 13 Sep 2020 12:26:40 GMT");
    assert_eq!(rfc2822(1_700_000_000), "Tue, 14 Nov 2023 22:13:20 GMT");
}

#[test]
fn torznab_caps_matches_python() {
    let caps = String::from_utf8(torznab_caps()).unwrap();
    assert_eq!(
        caps,
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?><caps><server title=\"torrentds\"/>\
<limits max=\"100\" default=\"25\"/><searching>\
<search available=\"yes\" supportedParams=\"q\"/>\
<tv-search available=\"yes\" supportedParams=\"q,season,ep\"/>\
<movie-search available=\"yes\" supportedParams=\"q\"/>\
<audio-search available=\"yes\" supportedParams=\"q\"/>\
<book-search available=\"yes\" supportedParams=\"q\"/></searching><categories>\
<category id=\"2000\" name=\"Movies\"/><category id=\"5000\" name=\"TV\"/>\
<category id=\"3000\" name=\"Audio\"/><category id=\"4000\" name=\"PC\"/>\
<category id=\"7000\" name=\"Books\"/><category id=\"8000\" name=\"Other\"/>\
</categories></caps>"
    );
}

fn a_torrent() -> TorrentMeta {
    let info = sample_info();
    let ih = torrentds::sha1(&info);
    TorrentMeta {
        info_hash: ih,
        name: "Ubuntu 22.04 Desktop".to_string(),
        total_size: 1234,
        piece_length: 16384,
        piece_count: 1,
        files: vec![("test.txt".to_string(), 1234)],
        info_bytes: Some(info),
        info_hash_v2: None,
        version: "v1",
        content_id: None,
    }
}

async fn http_get(addr: std::net::SocketAddr, path: &str) -> (String, Vec<u8>) {
    let mut s = TcpStream::connect(addr).await.unwrap();
    s.write_all(format!("GET {path} HTTP/1.1\r\nHost: t\r\n\r\n").as_bytes())
        .await
        .unwrap();
    let mut resp = Vec::new();
    s.read_to_end(&mut resp).await.unwrap();
    let sep = resp.windows(4).position(|w| w == b"\r\n\r\n").unwrap();
    let head = String::from_utf8_lossy(&resp[..sep]).into_owned();
    (head, resp[sep + 4..].to_vec())
}

#[tokio::test]
async fn search_server_round_trip() {
    let mut store = Store::new();
    let meta = a_torrent();
    let ih_hex: String = torrentds::sha1(&sample_info())
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect();
    store.store_metadata(&meta, 1000);
    let server = SearchServer::new(Arc::new(Mutex::new(store)), None, "");
    let (addr, handle) = serve_search(server, "127.0.0.1:0".parse().unwrap())
        .await
        .unwrap();
    let _keep = handle;

    // health
    let (head, body) = http_get(addr, "/health").await;
    assert!(head.starts_with("HTTP/1.1 200"));
    assert!(String::from_utf8_lossy(&body).contains("\"torrents\":1"));

    // stats
    let (_h, body) = http_get(addr, "/api/stats").await;
    assert!(String::from_utf8_lossy(&body).contains("\"torrents\":1"));

    // search JSON finds it by prefix
    let (_h, body) = http_get(addr, "/api/search?q=ubuntu").await;
    let text = String::from_utf8_lossy(&body);
    assert!(text.contains("\"total\":1"), "api/search body: {text}");
    assert!(text.contains("Ubuntu 22.04 Desktop"));

    // HTML detail
    let (head, body) = http_get(addr, &format!("/t/{ih_hex}")).await;
    assert!(head.starts_with("HTTP/1.1 200"));
    assert!(String::from_utf8_lossy(&body).contains("Ubuntu 22.04 Desktop"));

    // rebuilt .torrent hashes back to the infohash
    let (head, body) = http_get(addr, &format!("/torrent/{ih_hex}.torrent")).await;
    assert!(head.contains("application/x-bittorrent"));
    let Ben::Dict(d) = torrentds::decode(&body).unwrap() else {
        panic!("torrent is a dict")
    };
    let Some(Ben::Dict(info)) = d.get(b"info".as_slice()) else {
        panic!("has info")
    };
    assert_eq!(
        torrentds::sha1(&encode(&Ben::Dict(info.clone()))),
        meta.info_hash
    );

    // torznab caps + search
    let (head, body) = http_get(addr, "/torznab/api?t=caps").await;
    assert!(head.contains("application/xml"));
    assert!(String::from_utf8_lossy(&body).contains("<caps>"));
    let (_h, body) = http_get(addr, "/torznab/api?t=search&q=ubuntu").await;
    let tz = String::from_utf8_lossy(&body);
    assert!(tz.contains("xmlns:torznab"));
    assert!(tz.contains("Ubuntu 22.04 Desktop"));
    assert!(tz.contains("<torznab:attr name=\"category\""));
    assert!(tz.contains("<torznab:attr name=\"infohash\""));

    // unknown torrent -> 404
    let (head, _b) = http_get(addr, "/t/deadbeef").await;
    assert!(head.starts_with("HTTP/1.1 404"));
}

// --------------------------------------------------------------------------- //
// Byte-identical page rendering (goldens/search.rs)
// --------------------------------------------------------------------------- //

fn py_stats() -> Stats {
    Stats {
        torrents: 1234,
        files: 0,
        total_size: 9_876_543_210,
        discovered: 0,
        pending: 0,
        blocked_infohash: 0,
        blocked_keyword: 0,
        hybrid_v2: 0,
        spam_flagged: 0,
    }
}

/// The generator's two fixture rows: one benign, one whose name, facet tags and
/// magnet are all attacker-shaped.
fn py_rows() -> Vec<SearchResult> {
    let mk = |ih: &str,
              name: &str,
              total_size: u64,
              file_count: usize,
              piece_count: usize,
              seen_count: u64,
              category: &str,
              tags: &str,
              magnet: String| SearchResult {
        infohash: ih.to_string(),
        name: name.to_string(),
        total_size,
        file_count,
        piece_count,
        seen_count,
        last_seen: 1_600_000_000,
        category: category.to_string(),
        version: "v1".into(),
        infohash_v2: None,
        tags: tags.to_string(),
        magnet,
        dup_count: 1,
        alt_infohashes: Vec::new(),
    };
    vec![
        mk(
            &"aa".repeat(20),
            "Ubuntu 22.04 Desktop",
            1_400_000_000,
            3,
            5340,
            7,
            "video",
            "res:1080p src:bluray vcodec:x265 year:2019",
            format!("magnet:?xt=urn:btih:{}&dn=Ubuntu%2022.04", "aa".repeat(20)),
        ),
        mk(
            &"bb".repeat(20),
            "<img src=x onerror=alert(1)> & \"quoted\" 'name'",
            512,
            1,
            1,
            1,
            "other",
            "res:<script>alert(2)</script> junk src:&amp;",
            format!("magnet:?xt=urn:btih:{}&dn=<script>", "bb".repeat(20)),
        ),
    ]
}

/// The generator's swarm fold: only the first row carries seeders/leechers.
fn py_swarm() -> HashMap<String, (u64, u64)> {
    let mut sw = HashMap::new();
    sw.insert("aa".repeat(20), (12u64, 34u64));
    sw
}

/// Replace the constant stylesheet with the generator's marker.
fn elide(page: Vec<u8>) -> String {
    String::from_utf8(page).unwrap().replace(
        &format!("<style>{PAGE_CSS}</style>"),
        "<style>@CSS@</style>",
    )
}

fn golden(name: &str) -> &'static str {
    PAGES
        .iter()
        .find(|(k, _)| *k == name)
        .map(|(_, v)| *v)
        .unwrap_or_else(|| panic!("no golden named {name:?}; regenerate tests/goldens/search.rs"))
}

/// Assert one rendered page is byte-identical to the reference's.
#[track_caller]
fn same(name: &str, rendered: Vec<u8>) {
    let want = golden(name);
    let got = elide(rendered);
    if got != want {
        let at = got
            .as_bytes()
            .iter()
            .zip(want.as_bytes())
            .position(|(a, b)| a != b)
            .unwrap_or_else(|| got.len().min(want.len()));
        let lo = at.saturating_sub(60);
        panic!(
            "{name}: diverges at byte {at} (rust {} B, python {} B)\n  rust:   …{}…\n  python: …{}…",
            got.len(),
            want.len(),
            &got[lo..(at + 60).min(got.len())],
            &want[lo..(at + 60).min(want.len())],
        );
    }
}

#[test]
fn page_css_matches_python() {
    assert_eq!(PAGE_CSS, PY_CSS);
    assert_eq!(PAGE_CSS.len(), 1427);
}

#[test]
fn rendered_search_pages_match_python() {
    let rows = py_rows();
    let sw = py_swarm();
    let stats = py_stats();
    let any = UiFilters::default();

    same(
        "search_empty",
        render_results(
            "nothing matches this",
            &[],
            &stats,
            &sw,
            &any,
            Page {
                total: 0,
                limit: 25,
                offset: 0,
            },
        ),
    );
    same(
        "search_page1_next",
        render_results(
            "ubuntu",
            &rows[..1],
            &stats,
            &sw,
            &any,
            Page {
                total: 30,
                limit: 25,
                offset: 0,
            },
        ),
    );
    same(
        "search_page2_filtered",
        render_results(
            PY_HOSTILE_QUERY,
            &rows,
            &stats,
            &sw,
            &UiFilters {
                category: Some("video".into()),
                min_size: Some(104_857_600),
                since: Some(86400),
                order: Order::Latest,
            },
            Page {
                total: 42,
                limit: 25,
                offset: 25,
            },
        ),
    );
    same(
        "search_order_oldest",
        render_results(
            "",
            &rows[..1],
            &stats,
            &sw,
            &UiFilters {
                order: Order::Oldest,
                ..UiFilters::default()
            },
            Page {
                total: 1,
                limit: 25,
                offset: 0,
            },
        ),
    );
    same(
        "search_hostile_no_filters",
        render_results(
            PY_HOSTILE_QUERY,
            &[],
            &stats,
            &sw,
            &UiFilters {
                category: Some("<script>".into()),
                ..UiFilters::default()
            },
            Page {
                total: 100,
                limit: 10,
                offset: 10,
            },
        ),
    );
}

#[test]
fn rendered_browse_pages_match_python() {
    let rows = py_rows();
    let stats = py_stats();
    same(
        "browse",
        render_browse(&[("video", 12), ("audio", 3), ("other", 1)], &rows, &stats),
    );
    same("browse_empty", render_browse(&[], &[], &stats));
}

// --------------------------------------------------------------------------- //
// End-to-end: the served page carries the real total, the filters and the pager
// --------------------------------------------------------------------------- //

fn nth_torrent(n: u8) -> TorrentMeta {
    // A plausible single-file video release: the piece count matches the size, so
    // the store's spam heuristic leaves it in the index.
    let name = format!("Debian.12.{n}.Live.amd64.1080p.x264.mkv");
    let mut m = std::collections::BTreeMap::new();
    m.insert(b"length".to_vec(), Ben::Int(1_400_000_000));
    m.insert(b"name".to_vec(), Ben::Bytes(name.clone().into_bytes()));
    m.insert(b"piece length".to_vec(), Ben::Int(262_144));
    m.insert(b"pieces".to_vec(), Ben::Bytes(vec![n; 20]));
    let info = encode(&Ben::Dict(m));
    TorrentMeta {
        info_hash: torrentds::sha1(&info),
        name: name.clone(),
        total_size: 1_400_000_000,
        piece_length: 262_144,
        piece_count: 5341,
        files: vec![(name, 1_400_000_000)],
        info_bytes: Some(info),
        info_hash_v2: None,
        version: "v1",
        content_id: None,
    }
}

#[tokio::test]
async fn served_page_paginates_over_the_real_total() {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs();
    let mut store = Store::new();
    for n in 1..=3u8 {
        store.store_metadata(&nth_torrent(n), now);
    }
    let server = SearchServer::new(Arc::new(Mutex::new(store)), None, "");
    let (addr, handle) = serve_search(server, "127.0.0.1:0".parse().unwrap())
        .await
        .unwrap();
    let _keep = handle;

    // Page 1 of 3 at limit=1: the count is the MATCH total (3), not the page
    // size (1), and there is a `next` link but no `prev`.
    let (_h, body) = http_get(addr, "/search?limit=1").await;
    let html = String::from_utf8(body).unwrap();
    assert!(html.contains("&middot; 3 match</p>"), "{html}");
    assert_eq!(html.matches("<div class=result>").count(), 1);
    assert!(html.contains("<div class=filters><select name=category>"));
    assert!(html.contains("<a href='/search?limit=1&offset=1'>next &rarr;</a>"));
    assert!(!html.contains("prev"));

    // Page 2 keeps the query and every filter in BOTH links, and the form
    // reflects the active filter/order back as the selected options.
    let (_h, body) = http_get(
        addr,
        "/search?q=debian&limit=1&offset=1&category=video&since=86400&order=latest",
    )
    .await;
    let html = String::from_utf8(body).unwrap();
    assert!(html.contains("&middot; 3 match</p>"), "{html}");
    assert!(html.contains("<option value='video' selected>Video</option>"));
    assert!(html.contains("<option value='86400' selected>Past day</option>"));
    assert!(html.contains("<option value='latest' selected>Latest</option>"));
    assert!(
        html.contains(
            "<a href='/search?q=debian&limit=1&offset=0&category=video&since=86400\
             &order=latest'>&larr; prev</a>"
        ),
        "{html}"
    );
    assert!(
        html.contains(
            "<a href='/search?q=debian&limit=1&offset=2&category=video&since=86400\
             &order=latest'>next &rarr;</a>"
        ),
        "{html}"
    );

    // `/recent` pins the order to Latest and paginates over the same real total.
    let (_h, body) = http_get(addr, "/recent?limit=2").await;
    let html = String::from_utf8(body).unwrap();
    assert!(html.contains("&middot; 3 match</p>"), "{html}");
    assert!(html.contains("<option value='latest' selected>Latest</option>"));
    assert!(
        html.contains("<a href='/search?limit=2&offset=2&order=latest'>next &rarr;</a>"),
        "{html}"
    );

    // A category listing keeps the category in its pager links.
    let (_h, body) = http_get(addr, "/browse?category=video&limit=2").await;
    let html = String::from_utf8(body).unwrap();
    assert!(html.contains("&middot; 3 match</p>"), "{html}");
    assert!(
        html.contains(
            "<a href='/search?limit=2&offset=2&category=video&order=latest'>next &rarr;</a>"
        ),
        "{html}"
    );

    // `/browse` tiles use the `.filters` container the stylesheet styles.
    let (_h, body) = http_get(addr, "/browse").await;
    let html = String::from_utf8(body).unwrap();
    assert!(
        html.contains("<h3>Categories</h3><div class=filters>"),
        "{html}"
    );
}
