<?php
declare(strict_types=1);

namespace AstrX\Media;

use AstrX\Media\Diagnostic\MediaDbDiagnostic;
use AstrX\Result\Diagnostics;
use AstrX\Result\DiagnosticLevel;
use AstrX\Result\Result;
use PDO;
use PDOException;

/**
 * Data access for the media module: the `media` table of re-encoded, uploaded
 * files that can be re-used across content pages.
 *
 * All queries are bound; native prepares mean integer columns come back as ints.
 * `created_by` is a BINARY(16) user id, stored via UNHEX() and read back as a
 * 32-char lowercase hex string via LOWER(HEX()) — the same convention as the
 * comment/user repositories. The stored `name` is a UNIQUE, path-safe token
 * generated by MediaService, never a client value.
 *
 * @phpstan-type MediaRow array{id:int,name:string,orig_name:string,mime:string,ext:string,size:int,sha256:string,width:int,height:int,created_by:?string,created_at:string}
 */
final class MediaRepository
{
    public function __construct(private readonly PDO $pdo) {}

    /**
     * Insert one media row. Returns the new id.
     *
     * @param array{name:string,orig_name:string,mime:string,ext:string,size:int,sha256:string,width:int,height:int,created_by:?string} $row
     * @return Result<int>
     */
    public function insert(array $row): Result
    {
        try {
            $stmt = $this->pdo->prepare(
                'INSERT INTO `media`
                    (`name`, `orig_name`, `mime`, `ext`, `size`, `sha256`, `width`, `height`, `created_by`)
                 VALUES
                    (:name, :orig_name, :mime, :ext, :size, :sha256, :width, :height, UNHEX(:created_by))'
            );
            $stmt->bindValue(':name',       $row['name']);
            $stmt->bindValue(':orig_name',  $row['orig_name']);
            $stmt->bindValue(':mime',       $row['mime']);
            $stmt->bindValue(':ext',        $row['ext']);
            $stmt->bindValue(':size',       max(0, $row['size']),   PDO::PARAM_INT);
            $stmt->bindValue(':sha256',     $row['sha256']);
            $stmt->bindValue(':width',      max(0, $row['width']),  PDO::PARAM_INT);
            $stmt->bindValue(':height',     max(0, $row['height']), PDO::PARAM_INT);
            // A NULL / malformed uploader id stores NULL (UNHEX(NULL) IS NULL).
            $cb = $this->hexOrNull($row['created_by']);
            $stmt->bindValue(':created_by', $cb, $cb === null ? PDO::PARAM_NULL : PDO::PARAM_STR);
            $stmt->execute();
            return Result::ok((int) $this->pdo->lastInsertId());
        } catch (PDOException $e) {
            return Result::err(0, $this->diag($e));
        }
    }

    /**
     * Every media row, newest first (for the admin grid).
     *
     * @return Result<list<array{id:int,name:string,orig_name:string,mime:string,ext:string,size:int,sha256:string,width:int,height:int,created_by:?string,created_at:string}>>
     */
    public function all(): Result
    {
        try {
            $stmt = $this->pdo->query(
                'SELECT `id`, `name`, `orig_name`, `mime`, `ext`, `size`, `sha256`,
                        `width`, `height`, LOWER(HEX(`created_by`)) AS `created_by`, `created_at`
                   FROM `media`
                  ORDER BY `id` DESC'
            );
            $out = [];
            if ($stmt !== false) {
                /** @var array<string,mixed> $r */
                foreach ($stmt->fetchAll(PDO::FETCH_ASSOC) as $r) {
                    $out[] = $this->row($r);
                }
            }
            return Result::ok($out);
        } catch (PDOException $e) {
            return Result::err([], $this->diag($e));
        }
    }

    /** @return Result<?array{id:int,name:string,orig_name:string,mime:string,ext:string,size:int,sha256:string,width:int,height:int,created_by:?string,created_at:string}> */
    public function byId(int $id): Result
    {
        return $this->one(
            'SELECT `id`, `name`, `orig_name`, `mime`, `ext`, `size`, `sha256`,
                    `width`, `height`, LOWER(HEX(`created_by`)) AS `created_by`, `created_at`
               FROM `media` WHERE `id` = :i LIMIT 1',
            ':i', $id, PDO::PARAM_INT
        );
    }

    /** @return Result<?array{id:int,name:string,orig_name:string,mime:string,ext:string,size:int,sha256:string,width:int,height:int,created_by:?string,created_at:string}> */
    public function byName(string $name): Result
    {
        return $this->one(
            'SELECT `id`, `name`, `orig_name`, `mime`, `ext`, `size`, `sha256`,
                    `width`, `height`, LOWER(HEX(`created_by`)) AS `created_by`, `created_at`
               FROM `media` WHERE `name` = :n LIMIT 1',
            ':n', $name, PDO::PARAM_STR
        );
    }

    /**
     * Rename a media row, enforcing the UNIQUE `name` constraint.
     *
     * Returns ok(true) on success, ok(false) if the target name is already taken
     * (a rejected business rule, not a failure), and err(false) on a DB error. A
     * concurrent insert that steals the name between the pre-check and the UPDATE
     * is caught by the UNIQUE index and surfaces as err(false) — never corruption.
     *
     * @return Result<bool>
     */
    public function rename(int $id, string $newName): Result
    {
        try {
            $chk = $this->pdo->prepare('SELECT `id` FROM `media` WHERE `name` = :n AND `id` <> :i LIMIT 1');
            $chk->bindValue(':n', $newName);
            $chk->bindValue(':i', $id, PDO::PARAM_INT);
            $chk->execute();
            if (is_array($chk->fetch(PDO::FETCH_ASSOC))) {
                return Result::ok(false); // name taken
            }

            $stmt = $this->pdo->prepare('UPDATE `media` SET `name` = :n WHERE `id` = :i');
            $stmt->bindValue(':n', $newName);
            $stmt->bindValue(':i', $id, PDO::PARAM_INT);
            $stmt->execute();
            return Result::ok(true);
        } catch (PDOException $e) {
            return Result::err(false, $this->diag($e));
        }
    }

    /**
     * Delete a media row, returning the deleted row so the caller can unlink its
     * file from disk. ok(null) when no such id exists; err(null) on a DB error.
     *
     * @return Result<?array{id:int,name:string,orig_name:string,mime:string,ext:string,size:int,sha256:string,width:int,height:int,created_by:?string,created_at:string}>
     */
    public function delete(int $id): Result
    {
        try {
            $found = $this->byId($id);
            if (!$found->isOk()) {
                return $found;
            }
            /** @var array{id:int,name:string,orig_name:string,mime:string,ext:string,size:int,sha256:string,width:int,height:int,created_by:?string,created_at:string}|null $row */
            $row = $found->unwrap();
            if ($row === null) {
                return Result::ok(null);
            }
            $stmt = $this->pdo->prepare('DELETE FROM `media` WHERE `id` = :i');
            $stmt->bindValue(':i', $id, PDO::PARAM_INT);
            $stmt->execute();
            return Result::ok($row);
        } catch (PDOException $e) {
            return Result::err(null, $this->diag($e));
        }
    }

    // -------------------------------------------------------------------------

    /**
     * @return Result<?array{id:int,name:string,orig_name:string,mime:string,ext:string,size:int,sha256:string,width:int,height:int,created_by:?string,created_at:string}>
     */
    private function one(string $sql, string $param, int|string $value, int $type): Result
    {
        try {
            $stmt = $this->pdo->prepare($sql);
            $stmt->bindValue($param, $value, $type);
            $stmt->execute();
            $row = $stmt->fetch(PDO::FETCH_ASSOC);
            if (!is_array($row)) {
                return Result::ok(null);
            }
            /** @var array<string,mixed> $row */
            return Result::ok($this->row($row));
        } catch (PDOException $e) {
            return Result::err(null, $this->diag($e));
        }
    }

    /**
     * @param array<string,mixed> $r
     * @return array{id:int,name:string,orig_name:string,mime:string,ext:string,size:int,sha256:string,width:int,height:int,created_by:?string,created_at:string}
     */
    private function row(array $r): array
    {
        $cb = $r['created_by'] ?? null;
        return [
            'id'         => $this->i($r['id'] ?? null),
            'name'       => $this->s($r['name'] ?? null),
            'orig_name'  => $this->s($r['orig_name'] ?? null),
            'mime'       => $this->s($r['mime'] ?? null),
            'ext'        => $this->s($r['ext'] ?? null),
            'size'       => $this->i($r['size'] ?? null),
            'sha256'     => $this->s($r['sha256'] ?? null),
            'width'      => $this->i($r['width'] ?? null),
            'height'     => $this->i($r['height'] ?? null),
            'created_by' => (is_string($cb) && $cb !== '') ? strtolower($cb) : null,
            'created_at' => $this->s($r['created_at'] ?? null),
        ];
    }

    /** Accept a 32-char hex user id, else null (stored as NULL). */
    private function hexOrNull(?string $hex): ?string
    {
        if ($hex === null) {
            return null;
        }
        $hex = strtolower(trim($hex));
        return ($hex !== '' && strlen($hex) === 32 && ctype_xdigit($hex)) ? $hex : null;
    }

    private function diag(PDOException $e): Diagnostics
    {
        return Diagnostics::of(new MediaDbDiagnostic('astrx.media/db_error', DiagnosticLevel::ERROR, $e->getMessage()));
    }

    private function s(mixed $v): string
    {
        return is_scalar($v) ? (string) $v : '';
    }

    private function i(mixed $v): int
    {
        return is_int($v) ? $v : (is_numeric($v) ? (int) $v : 0);
    }
}
